// <auto-generated />
using System;
using Corela15.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Corela15.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(Corela15DbContext))]
    [Migration("20260812230024_Nivel1_MotorContable")]
    partial class Nivel1_MotorContable
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Corela15.Domain.Clientes.Cliente", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreadoEn")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("creado_en");

                    b.Property<string>("CreadoPor")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("creado_por");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("estado");

                    b.Property<int>("IdAgencia")
                        .HasColumnType("integer")
                        .HasColumnName("id_agencia");

                    b.Property<Guid>("IdPersona")
                        .HasColumnType("uuid")
                        .HasColumnName("id_persona");

                    b.Property<Guid?>("IdUsuarioOficial")
                        .HasColumnType("uuid")
                        .HasColumnName("id_usuario_oficial");

                    b.Property<DateTimeOffset?>("ModificadoEn")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("modificado_en");

                    b.Property<string>("ModificadoPor")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("modificado_por");

                    b.Property<string>("Numero")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("numero");

                    b.HasKey("Id")
                        .HasName("pk_cliente");

                    b.HasIndex("IdAgencia")
                        .HasDatabaseName("ix_cliente_id_agencia");

                    b.HasIndex("IdPersona")
                        .IsUnique()
                        .HasDatabaseName("ix_cliente_persona_unico_si_activo")
                        .HasFilter("estado = 'Activo'");

                    b.HasIndex("Numero")
                        .IsUnique()
                        .HasDatabaseName("ix_cliente_numero");

                    b.ToTable("cliente", "clientes");
                });

            modelBuilder.Entity("Corela15.Domain.Contabilidad.ComprobanteContable", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreadoEn")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("creado_en");

                    b.Property<string>("CreadoPor")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("creado_por");

                    b.Property<string>("Descripcion")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("descripcion");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("estado");

                    b.Property<DateOnly>("Fecha")
                        .HasColumnType("date")
                        .HasColumnName("fecha");

                    b.Property<int>("IdAgencia")
                        .HasColumnType("integer")
                        .HasColumnName("id_agencia");

                    b.Property<int>("IdTipoComprobante")
                        .HasColumnType("integer")
                        .HasColumnName("id_tipo_comprobante");

                    b.Property<DateTimeOffset?>("ModificadoEn")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("modificado_en");

                    b.Property<string>("ModificadoPor")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("modificado_por");

                    b.Property<long>("Numero")
                        .HasColumnType("bigint")
                        .HasColumnName("numero");

                    b.HasKey("Id")
                        .HasName("pk_comprobante_contable");

                    b.HasIndex("IdAgencia")
                        .HasDatabaseName("ix_comprobante_contable_id_agencia");

                    b.HasIndex("IdTipoComprobante", "Numero")
                        .IsUnique()
                        .HasDatabaseName("ix_comprobante_contable_id_tipo_comprobante_numero");

                    b.ToTable("comprobante_contable", "contabilidad");
                });

            modelBuilder.Entity("Corela15.Domain.Contabilidad.CuentaContable", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<bool>("Activa")
                        .HasColumnType("boolean")
                        .HasColumnName("activa");

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("codigo");

                    b.Property<DateTimeOffset>("CreadoEn")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("creado_en");

                    b.Property<string>("CreadoPor")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("creado_por");

                    b.Property<bool>("EsMayor")
                        .HasColumnType("boolean")
                        .HasColumnName("es_mayor");

                    b.Property<string>("Grupo")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("grupo");

                    b.Property<Guid?>("IdCuentaPadre")
                        .HasColumnType("uuid")
                        .HasColumnName("id_cuenta_padre");

                    b.Property<DateTimeOffset?>("ModificadoEn")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("modificado_en");

                    b.Property<string>("ModificadoPor")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("modificado_por");

                    b.Property<string>("Naturaleza")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("naturaleza");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("nombre");

                    b.HasKey("Id")
                        .HasName("pk_cuenta_contable");

                    b.HasIndex("Codigo")
                        .IsUnique()
                        .HasDatabaseName("ix_cuenta_contable_codigo");

                    b.HasIndex("IdCuentaPadre")
                        .HasDatabaseName("ix_cuenta_contable_id_cuenta_padre");

                    b.ToTable("cuenta_contable", "contabilidad");
                });

            modelBuilder.Entity("Corela15.Domain.Contabilidad.MovimientoComprobanteContable", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<decimal>("Credito")
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("credito");

                    b.Property<decimal>("Debito")
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("debito");

                    b.Property<string>("Descripcion")
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)")
                        .HasColumnName("descripcion");

                    b.Property<Guid>("IdComprobante")
                        .HasColumnType("uuid")
                        .HasColumnName("id_comprobante");

                    b.Property<Guid>("IdCuentaContable")
                        .HasColumnType("uuid")
                        .HasColumnName("id_cuenta_contable");

                    b.Property<int>("NumeroLinea")
                        .HasColumnType("integer")
                        .HasColumnName("numero_linea");

                    b.HasKey("Id")
                        .HasName("pk_movimiento_comprobante_contable");

                    b.HasIndex("IdCuentaContable")
                        .HasDatabaseName("ix_movimiento_comprobante_contable_id_cuenta_contable");

                    b.HasIndex("IdComprobante", "NumeroLinea")
                        .IsUnique()
                        .HasDatabaseName("ix_movimiento_comprobante_contable_id_comprobante_numero_linea");

                    b.ToTable("movimiento_comprobante_contable", "contabilidad", t =>
                        {
                            t.HasCheckConstraint("ck_movimiento_debito_o_credito", "(debito = 0 OR credito = 0) AND (debito + credito) > 0");
                        });
                });

            modelBuilder.Entity("Corela15.Domain.Contabilidad.SaldoContable", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("IdCuentaContable")
                        .HasColumnType("uuid")
                        .HasColumnName("id_cuenta_contable");

                    b.Property<DateOnly>("Periodo")
                        .HasColumnType("date")
                        .HasColumnName("periodo");

                    b.Property<decimal>("SaldoFinal")
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("saldo_final");

                    b.Property<decimal>("TotalCreditos")
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("total_creditos");

                    b.Property<decimal>("TotalDebitos")
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("total_debitos");

                    b.HasKey("Id")
                        .HasName("pk_saldo_contable");

                    b.HasIndex("IdCuentaContable", "Periodo")
                        .IsUnique()
                        .HasDatabaseName("ix_saldo_contable_id_cuenta_contable_periodo");

                    b.ToTable("saldo_contable", "contabilidad");
                });

            modelBuilder.Entity("Corela15.Domain.Contabilidad.TipoComprobanteContable", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("codigo");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("nombre");

                    b.HasKey("Id")
                        .HasName("pk_tipo_comprobante_contable");

                    b.HasIndex("Codigo")
                        .IsUnique()
                        .HasDatabaseName("ix_tipo_comprobante_contable_codigo");

                    b.ToTable("tipo_comprobante_contable", "contabilidad");
                });

            modelBuilder.Entity("Corela15.Domain.General.Agencia", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("Activa")
                        .HasColumnType("boolean")
                        .HasColumnName("activa");

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("codigo");

                    b.Property<bool>("EsOperativa")
                        .HasColumnType("boolean")
                        .HasColumnName("es_operativa");

                    b.Property<int>("IdEmpresa")
                        .HasColumnType("integer")
                        .HasColumnName("id_empresa");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("nombre");

                    b.HasKey("Id")
                        .HasName("pk_agencia");

                    b.HasIndex("IdEmpresa", "Codigo")
                        .IsUnique()
                        .HasDatabaseName("ix_agencia_id_empresa_codigo");

                    b.ToTable("agencia", "general");
                });

            modelBuilder.Entity("Corela15.Domain.General.Empresa", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("codigo");

                    b.Property<int>("IdMoneda")
                        .HasColumnType("integer")
                        .HasColumnName("id_moneda");

                    b.Property<int>("IdPais")
                        .HasColumnType("integer")
                        .HasColumnName("id_pais");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("nombre");

                    b.Property<string>("Ruc")
                        .IsRequired()
                        .HasMaxLength(13)
                        .HasColumnType("character varying(13)")
                        .HasColumnName("ruc");

                    b.HasKey("Id")
                        .HasName("pk_empresa");

                    b.HasIndex("IdMoneda")
                        .HasDatabaseName("ix_empresa_id_moneda");

                    b.HasIndex("IdPais")
                        .HasDatabaseName("ix_empresa_id_pais");

                    b.HasIndex("Ruc")
                        .IsUnique()
                        .HasDatabaseName("ix_empresa_ruc");

                    b.ToTable("empresa", "general");
                });

            modelBuilder.Entity("Corela15.Domain.General.Moneda", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("character varying(3)")
                        .HasColumnName("codigo");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("nombre");

                    b.Property<string>("Simbolo")
                        .IsRequired()
                        .HasMaxLength(5)
                        .HasColumnType("character varying(5)")
                        .HasColumnName("simbolo");

                    b.HasKey("Id")
                        .HasName("pk_moneda");

                    b.HasIndex("Codigo")
                        .IsUnique()
                        .HasDatabaseName("ix_moneda_codigo");

                    b.ToTable("moneda", "general");
                });

            modelBuilder.Entity("Corela15.Domain.General.Pais", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("character varying(3)")
                        .HasColumnName("codigo");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("nombre");

                    b.HasKey("Id")
                        .HasName("pk_pais");

                    b.HasIndex("Codigo")
                        .IsUnique()
                        .HasDatabaseName("ix_pais_codigo");

                    b.ToTable("pais", "general");
                });

            modelBuilder.Entity("Corela15.Domain.General.TipoIdentificacion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("codigo");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("nombre");

                    b.HasKey("Id")
                        .HasName("pk_tipo_identificacion");

                    b.HasIndex("Codigo")
                        .IsUnique()
                        .HasDatabaseName("ix_tipo_identificacion_codigo");

                    b.ToTable("tipo_identificacion", "general");
                });

            modelBuilder.Entity("Corela15.Domain.Seguridad.AccionIngresoUsuario", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityAlwaysColumn(b.Property<long>("Id"));

                    b.Property<string>("Detalle")
                        .HasColumnType("text")
                        .HasColumnName("detalle");

                    b.Property<string>("DireccionIp")
                        .HasMaxLength(45)
                        .HasColumnType("character varying(45)")
                        .HasColumnName("direccion_ip");

                    b.Property<bool>("Exitoso")
                        .HasColumnType("boolean")
                        .HasColumnName("exitoso");

                    b.Property<DateTimeOffset>("FechaHora")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fecha_hora");

                    b.Property<Guid>("IdUsuario")
                        .HasColumnType("uuid")
                        .HasColumnName("id_usuario");

                    b.HasKey("Id")
                        .HasName("pk_accion_ingreso_usuario");

                    b.HasIndex("FechaHora")
                        .HasDatabaseName("ix_accion_ingreso_usuario_fecha_hora");

                    b.HasIndex("IdUsuario")
                        .HasDatabaseName("ix_accion_ingreso_usuario_id_usuario");

                    b.ToTable("accion_ingreso_usuario", "seguridad");
                });

            modelBuilder.Entity("Corela15.Domain.Seguridad.Rol", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("Nivel")
                        .HasColumnType("integer")
                        .HasColumnName("nivel");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("nombre");

                    b.HasKey("Id")
                        .HasName("pk_rol");

                    b.HasIndex("Nombre")
                        .IsUnique()
                        .HasDatabaseName("ix_rol_nombre");

                    b.ToTable("rol", "seguridad");
                });

            modelBuilder.Entity("Corela15.Domain.Seguridad.Usuario", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<bool>("Activo")
                        .HasColumnType("boolean")
                        .HasColumnName("activo");

                    b.Property<DateTimeOffset>("CreadoEn")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("creado_en");

                    b.Property<string>("CreadoPor")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("creado_por");

                    b.Property<string>("HashContrasena")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("hash_contrasena");

                    b.Property<int>("IdAgencia")
                        .HasColumnType("integer")
                        .HasColumnName("id_agencia");

                    b.Property<Guid?>("IdPersona")
                        .HasColumnType("uuid")
                        .HasColumnName("id_persona");

                    b.Property<DateTimeOffset?>("ModificadoEn")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("modificado_en");

                    b.Property<string>("ModificadoPor")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("modificado_por");

                    b.Property<string>("NombreUsuario")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("nombre_usuario");

                    b.Property<bool>("PuedeIngresarSistema")
                        .HasColumnType("boolean")
                        .HasColumnName("puede_ingresar_sistema");

                    b.Property<bool>("TieneBloqueo")
                        .HasColumnType("boolean")
                        .HasColumnName("tiene_bloqueo");

                    b.HasKey("Id")
                        .HasName("pk_usuario");

                    b.HasIndex("IdAgencia")
                        .HasDatabaseName("ix_usuario_id_agencia");

                    b.HasIndex("IdPersona")
                        .HasDatabaseName("ix_usuario_id_persona");

                    b.HasIndex("NombreUsuario")
                        .IsUnique()
                        .HasDatabaseName("ix_usuario_nombre_usuario");

                    b.ToTable("usuario", "seguridad");
                });

            modelBuilder.Entity("Corela15.Domain.Seguridad.UsuarioRol", b =>
                {
                    b.Property<Guid>("IdUsuario")
                        .HasColumnType("uuid")
                        .HasColumnName("id_usuario");

                    b.Property<int>("IdRol")
                        .HasColumnType("integer")
                        .HasColumnName("id_rol");

                    b.Property<bool>("Activo")
                        .HasColumnType("boolean")
                        .HasColumnName("activo");

                    b.Property<DateTimeOffset>("AsignadoEn")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("asignado_en");

                    b.HasKey("IdUsuario", "IdRol")
                        .HasName("pk_usuario_rol");

                    b.HasIndex("IdRol")
                        .HasDatabaseName("ix_usuario_rol_id_rol");

                    b.ToTable("usuario_rol", "seguridad");
                });

            modelBuilder.Entity("Corela15.Domain.Sujeto.Persona", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<decimal?>("Activos")
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("activos");

                    b.Property<string>("Barrio")
                        .HasColumnType("text")
                        .HasColumnName("barrio");

                    b.Property<string>("CallePrincipal")
                        .HasColumnType("text")
                        .HasColumnName("calle_principal");

                    b.Property<DateTimeOffset>("CreadoEn")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("creado_en");

                    b.Property<string>("CreadoPor")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("creado_por");

                    b.Property<decimal?>("Egresos")
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("egresos");

                    b.Property<string>("Email")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("email");

                    b.Property<int?>("IdActividadEconomica")
                        .HasColumnType("integer")
                        .HasColumnName("id_actividad_economica");

                    b.Property<int?>("IdPais")
                        .HasColumnType("integer")
                        .HasColumnName("id_pais");

                    b.Property<int>("IdTipoIdentificacion")
                        .HasColumnType("integer")
                        .HasColumnName("id_tipo_identificacion");

                    b.Property<string>("Identificacion")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("identificacion");

                    b.Property<decimal?>("Ingresos")
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("ingresos");

                    b.Property<DateTimeOffset?>("ModificadoEn")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("modificado_en");

                    b.Property<string>("ModificadoPor")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("modificado_por");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)")
                        .HasColumnName("nombre");

                    b.Property<string>("NumeroCasa")
                        .HasColumnType("text")
                        .HasColumnName("numero_casa");

                    b.Property<decimal?>("Pasivos")
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("pasivos");

                    b.HasKey("Id")
                        .HasName("pk_persona");

                    b.HasIndex("IdPais")
                        .HasDatabaseName("ix_persona_id_pais");

                    b.HasIndex("IdTipoIdentificacion", "Identificacion")
                        .IsUnique()
                        .HasDatabaseName("ix_persona_id_tipo_identificacion_identificacion");

                    b.ToTable("persona", "sujeto");
                });

            modelBuilder.Entity("Corela15.Domain.Sujeto.PersonaJuridica", b =>
                {
                    b.Property<Guid>("IdPersona")
                        .HasColumnType("uuid")
                        .HasColumnName("id_persona");

                    b.Property<bool>("EsGrupo")
                        .HasColumnType("boolean")
                        .HasColumnName("es_grupo");

                    b.Property<bool>("EsInstitucionBancaria")
                        .HasColumnType("boolean")
                        .HasColumnName("es_institucion_bancaria");

                    b.Property<bool>("EsPublica")
                        .HasColumnType("boolean")
                        .HasColumnName("es_publica");

                    b.Property<DateOnly>("FechaCreacion")
                        .HasColumnType("date")
                        .HasColumnName("fecha_creacion");

                    b.Property<int?>("PaisConstitucion")
                        .HasColumnType("integer")
                        .HasColumnName("pais_constitucion");

                    b.Property<string>("RazonSocial")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)")
                        .HasColumnName("razon_social");

                    b.HasKey("IdPersona")
                        .HasName("pk_persona_juridica");

                    b.ToTable("persona_juridica", "sujeto");
                });

            modelBuilder.Entity("Corela15.Domain.Sujeto.PersonaNatural", b =>
                {
                    b.Property<Guid>("IdPersona")
                        .HasColumnType("uuid")
                        .HasColumnName("id_persona");

                    b.Property<string>("ApellidoMaterno")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("apellido_materno");

                    b.Property<string>("ApellidoPaterno")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("apellido_paterno");

                    b.Property<bool>("EsMasculino")
                        .HasColumnType("boolean")
                        .HasColumnName("es_masculino");

                    b.Property<bool>("EsPep")
                        .HasColumnType("boolean")
                        .HasColumnName("es_pep");

                    b.Property<DateOnly>("FechaNacimiento")
                        .HasColumnType("date")
                        .HasColumnName("fecha_nacimiento");

                    b.Property<string>("PrimerNombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("primer_nombre");

                    b.Property<string>("SegundoNombre")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("segundo_nombre");

                    b.HasKey("IdPersona")
                        .HasName("pk_persona_natural");

                    b.ToTable("persona_natural", "sujeto");
                });

            modelBuilder.Entity("Corela15.Domain.Clientes.Cliente", b =>
                {
                    b.HasOne("Corela15.Domain.General.Agencia", "Agencia")
                        .WithMany()
                        .HasForeignKey("IdAgencia")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_cliente_agencia_id_agencia");

                    b.HasOne("Corela15.Domain.Sujeto.Persona", "Persona")
                        .WithMany()
                        .HasForeignKey("IdPersona")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_cliente_personas_id_persona");

                    b.Navigation("Agencia");

                    b.Navigation("Persona");
                });

            modelBuilder.Entity("Corela15.Domain.Contabilidad.ComprobanteContable", b =>
                {
                    b.HasOne("Corela15.Domain.General.Agencia", "Agencia")
                        .WithMany()
                        .HasForeignKey("IdAgencia")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_comprobante_contable_agencia_id_agencia");

                    b.HasOne("Corela15.Domain.Contabilidad.TipoComprobanteContable", "TipoComprobante")
                        .WithMany()
                        .HasForeignKey("IdTipoComprobante")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_comprobante_contable_tipos_comprobante_contable_id_tipo_com");

                    b.Navigation("Agencia");

                    b.Navigation("TipoComprobante");
                });

            modelBuilder.Entity("Corela15.Domain.Contabilidad.CuentaContable", b =>
                {
                    b.HasOne("Corela15.Domain.Contabilidad.CuentaContable", "CuentaPadre")
                        .WithMany()
                        .HasForeignKey("IdCuentaPadre")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_cuenta_contable_cuenta_contable_id_cuenta_padre");

                    b.Navigation("CuentaPadre");
                });

            modelBuilder.Entity("Corela15.Domain.Contabilidad.MovimientoComprobanteContable", b =>
                {
                    b.HasOne("Corela15.Domain.Contabilidad.ComprobanteContable", "Comprobante")
                        .WithMany("Movimientos")
                        .HasForeignKey("IdComprobante")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_movimiento_comprobante_contable_comprobante_contable_id_com");

                    b.HasOne("Corela15.Domain.Contabilidad.CuentaContable", "CuentaContable")
                        .WithMany()
                        .HasForeignKey("IdCuentaContable")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_movimiento_comprobante_contable_cuenta_contable_id_cuenta_c");

                    b.Navigation("Comprobante");

                    b.Navigation("CuentaContable");
                });

            modelBuilder.Entity("Corela15.Domain.Contabilidad.SaldoContable", b =>
                {
                    b.HasOne("Corela15.Domain.Contabilidad.CuentaContable", "CuentaContable")
                        .WithMany()
                        .HasForeignKey("IdCuentaContable")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_saldo_contable_cuenta_contable_id_cuenta_contable");

                    b.Navigation("CuentaContable");
                });

            modelBuilder.Entity("Corela15.Domain.General.Agencia", b =>
                {
                    b.HasOne("Corela15.Domain.General.Empresa", "Empresa")
                        .WithMany()
                        .HasForeignKey("IdEmpresa")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_agencia_empresas_id_empresa");

                    b.Navigation("Empresa");
                });

            modelBuilder.Entity("Corela15.Domain.General.Empresa", b =>
                {
                    b.HasOne("Corela15.Domain.General.Moneda", "Moneda")
                        .WithMany()
                        .HasForeignKey("IdMoneda")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_empresa_monedas_id_moneda");

                    b.HasOne("Corela15.Domain.General.Pais", "Pais")
                        .WithMany()
                        .HasForeignKey("IdPais")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_empresa_paises_id_pais");

                    b.Navigation("Moneda");

                    b.Navigation("Pais");
                });

            modelBuilder.Entity("Corela15.Domain.Seguridad.AccionIngresoUsuario", b =>
                {
                    b.HasOne("Corela15.Domain.Seguridad.Usuario", "Usuario")
                        .WithMany()
                        .HasForeignKey("IdUsuario")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_accion_ingreso_usuario_usuarios_id_usuario");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("Corela15.Domain.Seguridad.Usuario", b =>
                {
                    b.HasOne("Corela15.Domain.General.Agencia", "Agencia")
                        .WithMany()
                        .HasForeignKey("IdAgencia")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_usuario_agencia_id_agencia");

                    b.HasOne("Corela15.Domain.Sujeto.Persona", "Persona")
                        .WithMany()
                        .HasForeignKey("IdPersona")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_usuario_persona_id_persona");

                    b.Navigation("Agencia");

                    b.Navigation("Persona");
                });

            modelBuilder.Entity("Corela15.Domain.Seguridad.UsuarioRol", b =>
                {
                    b.HasOne("Corela15.Domain.Seguridad.Rol", "Rol")
                        .WithMany("UsuarioRoles")
                        .HasForeignKey("IdRol")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_usuario_rol_rol_id_rol");

                    b.HasOne("Corela15.Domain.Seguridad.Usuario", "Usuario")
                        .WithMany("UsuarioRoles")
                        .HasForeignKey("IdUsuario")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_usuario_rol_usuario_id_usuario");

                    b.Navigation("Rol");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("Corela15.Domain.Sujeto.Persona", b =>
                {
                    b.HasOne("Corela15.Domain.General.Pais", "Pais")
                        .WithMany()
                        .HasForeignKey("IdPais")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_persona_pais_id_pais");

                    b.HasOne("Corela15.Domain.General.TipoIdentificacion", "TipoIdentificacion")
                        .WithMany()
                        .HasForeignKey("IdTipoIdentificacion")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_persona_tipos_identificacion_id_tipo_identificacion");

                    b.Navigation("Pais");

                    b.Navigation("TipoIdentificacion");
                });

            modelBuilder.Entity("Corela15.Domain.Sujeto.PersonaJuridica", b =>
                {
                    b.HasOne("Corela15.Domain.Sujeto.Persona", "Persona")
                        .WithOne("PersonaJuridica")
                        .HasForeignKey("Corela15.Domain.Sujeto.PersonaJuridica", "IdPersona")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_persona_juridica_persona_id_persona");

                    b.Navigation("Persona");
                });

            modelBuilder.Entity("Corela15.Domain.Sujeto.PersonaNatural", b =>
                {
                    b.HasOne("Corela15.Domain.Sujeto.Persona", "Persona")
                        .WithOne("PersonaNatural")
                        .HasForeignKey("Corela15.Domain.Sujeto.PersonaNatural", "IdPersona")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_persona_natural_persona_id_persona");

                    b.Navigation("Persona");
                });

            modelBuilder.Entity("Corela15.Domain.Contabilidad.ComprobanteContable", b =>
                {
                    b.Navigation("Movimientos");
                });

            modelBuilder.Entity("Corela15.Domain.Seguridad.Rol", b =>
                {
                    b.Navigation("UsuarioRoles");
                });

            modelBuilder.Entity("Corela15.Domain.Seguridad.Usuario", b =>
                {
                    b.Navigation("UsuarioRoles");
                });

            modelBuilder.Entity("Corela15.Domain.Sujeto.Persona", b =>
                {
                    b.Navigation("PersonaJuridica");

                    b.Navigation("PersonaNatural");
                });
#pragma warning restore 612, 618
        }
    }
}
