// <auto-generated />
using System;
using Corela15.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Corela15.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(Corela15DbContext))]
    [Migration("20260812234237_Nivel3_PlazoFijoYCredito")]
    partial class Nivel3_PlazoFijoYCredito
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Corela15.Domain.Ahorros.Cuenta", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreadoEn")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("creado_en");

                    b.Property<string>("CreadoPor")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("creado_por");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("estado");

                    b.Property<DateOnly>("FechaApertura")
                        .HasColumnType("date")
                        .HasColumnName("fecha_apertura");

                    b.Property<int>("IdAgencia")
                        .HasColumnType("integer")
                        .HasColumnName("id_agencia");

                    b.Property<int>("IdTipoCuenta")
                        .HasColumnType("integer")
                        .HasColumnName("id_tipo_cuenta");

                    b.Property<DateTimeOffset?>("ModificadoEn")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("modificado_en");

                    b.Property<string>("ModificadoPor")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("modificado_por");

                    b.Property<string>("Numero")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("numero");

                    b.HasKey("Id")
                        .HasName("pk_cuenta");

                    b.HasIndex("IdAgencia")
                        .HasDatabaseName("ix_cuenta_id_agencia");

                    b.HasIndex("IdTipoCuenta")
                        .HasDatabaseName("ix_cuenta_id_tipo_cuenta");

                    b.HasIndex("Numero")
                        .IsUnique()
                        .HasDatabaseName("ix_cuenta_numero");

                    b.ToTable("cuenta", "ahorros");
                });

            modelBuilder.Entity("Corela15.Domain.Ahorros.CuentaCliente", b =>
                {
                    b.Property<Guid>("IdCuenta")
                        .HasColumnType("uuid")
                        .HasColumnName("id_cuenta");

                    b.Property<Guid>("IdCliente")
                        .HasColumnType("uuid")
                        .HasColumnName("id_cliente");

                    b.Property<bool>("Principal")
                        .HasColumnType("boolean")
                        .HasColumnName("principal");

                    b.HasKey("IdCuenta", "IdCliente")
                        .HasName("pk_cuenta_cliente");

                    b.HasIndex("IdCliente")
                        .HasDatabaseName("ix_cuenta_cliente_id_cliente");

                    b.ToTable("cuenta_cliente", "ahorros");
                });

            modelBuilder.Entity("Corela15.Domain.Ahorros.CuentaItemSaldo", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<bool>("AcreditaPrestamo")
                        .HasColumnType("boolean")
                        .HasColumnName("acredita_prestamo");

                    b.Property<DateTimeOffset>("CreadoEn")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("creado_en");

                    b.Property<string>("CreadoPor")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("creado_por");

                    b.Property<Guid>("IdCuenta")
                        .HasColumnType("uuid")
                        .HasColumnName("id_cuenta");

                    b.Property<int>("IdItemSaldo")
                        .HasColumnType("integer")
                        .HasColumnName("id_item_saldo");

                    b.Property<DateTimeOffset?>("ModificadoEn")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("modificado_en");

                    b.Property<string>("ModificadoPor")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("modificado_por");

                    b.Property<decimal>("Saldo")
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("saldo");

                    b.HasKey("Id")
                        .HasName("pk_cuenta_item_saldo");

                    b.HasIndex("IdItemSaldo")
                        .HasDatabaseName("ix_cuenta_item_saldo_id_item_saldo");

                    b.HasIndex("IdCuenta", "IdItemSaldo")
                        .IsUnique()
                        .HasDatabaseName("ix_cuenta_item_saldo_id_cuenta_id_item_saldo");

                    b.ToTable("cuenta_item_saldo", "ahorros");
                });

            modelBuilder.Entity("Corela15.Domain.Ahorros.ItemSaldo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("codigo");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("nombre");

                    b.HasKey("Id")
                        .HasName("pk_item_saldo");

                    b.HasIndex("Codigo")
                        .IsUnique()
                        .HasDatabaseName("ix_item_saldo_codigo");

                    b.ToTable("item_saldo", "ahorros");
                });

            modelBuilder.Entity("Corela15.Domain.Ahorros.TipoCuenta", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("Activo")
                        .HasColumnType("boolean")
                        .HasColumnName("activo");

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("codigo");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("nombre");

                    b.Property<bool>("PermiteDebitoPrestamo")
                        .HasColumnType("boolean")
                        .HasColumnName("permite_debito_prestamo");

                    b.Property<decimal?>("SaldoMinimoConPrestamo")
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("saldo_minimo_con_prestamo");

                    b.HasKey("Id")
                        .HasName("pk_tipo_cuenta");

                    b.HasIndex("Codigo")
                        .IsUnique()
                        .HasDatabaseName("ix_tipo_cuenta_codigo");

                    b.ToTable("tipo_cuenta", "ahorros");
                });

            modelBuilder.Entity("Corela15.Domain.Ahorros.TipoCuentaItemSaldo", b =>
                {
                    b.Property<int>("IdTipoCuenta")
                        .HasColumnType("integer")
                        .HasColumnName("id_tipo_cuenta");

                    b.Property<int>("IdItemSaldo")
                        .HasColumnType("integer")
                        .HasColumnName("id_item_saldo");

                    b.HasKey("IdTipoCuenta", "IdItemSaldo")
                        .HasName("pk_tipo_cuenta_item_saldo");

                    b.HasIndex("IdItemSaldo")
                        .HasDatabaseName("ix_tipo_cuenta_item_saldo_id_item_saldo");

                    b.ToTable("tipo_cuenta_item_saldo", "ahorros");
                });

            modelBuilder.Entity("Corela15.Domain.Clientes.Cliente", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreadoEn")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("creado_en");

                    b.Property<string>("CreadoPor")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("creado_por");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("estado");

                    b.Property<int>("IdAgencia")
                        .HasColumnType("integer")
                        .HasColumnName("id_agencia");

                    b.Property<Guid>("IdPersona")
                        .HasColumnType("uuid")
                        .HasColumnName("id_persona");

                    b.Property<Guid?>("IdUsuarioOficial")
                        .HasColumnType("uuid")
                        .HasColumnName("id_usuario_oficial");

                    b.Property<DateTimeOffset?>("ModificadoEn")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("modificado_en");

                    b.Property<string>("ModificadoPor")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("modificado_por");

                    b.Property<string>("Numero")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("numero");

                    b.HasKey("Id")
                        .HasName("pk_cliente");

                    b.HasIndex("IdAgencia")
                        .HasDatabaseName("ix_cliente_id_agencia");

                    b.HasIndex("IdPersona")
                        .IsUnique()
                        .HasDatabaseName("ix_cliente_persona_unico_si_activo")
                        .HasFilter("estado = 'Activo'");

                    b.HasIndex("Numero")
                        .IsUnique()
                        .HasDatabaseName("ix_cliente_numero");

                    b.ToTable("cliente", "clientes");
                });

            modelBuilder.Entity("Corela15.Domain.Colocacion.ClasificacionCartera", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<bool>("Activo")
                        .HasColumnType("boolean")
                        .HasColumnName("activo");

                    b.Property<int>("DiasFin")
                        .HasColumnType("integer")
                        .HasColumnName("dias_fin");

                    b.Property<int>("DiasInicio")
                        .HasColumnType("integer")
                        .HasColumnName("dias_inicio");

                    b.Property<Guid>("IdCuentaContable")
                        .HasColumnType("uuid")
                        .HasColumnName("id_cuenta_contable");

                    b.Property<int>("IdTipoVencimiento")
                        .HasColumnType("integer")
                        .HasColumnName("id_tipo_vencimiento");

                    b.HasKey("Id")
                        .HasName("pk_clasificacion_cartera");

                    b.HasIndex("IdCuentaContable")
                        .HasDatabaseName("ix_clasificacion_cartera_id_cuenta_contable");

                    b.HasIndex("IdTipoVencimiento")
                        .HasDatabaseName("ix_clasificacion_cartera_id_tipo_vencimiento");

                    b.ToTable("clasificacion_cartera", "colocacion", t =>
                        {
                            t.HasCheckConstraint("ck_clasificacion_cartera_rango", "dias_fin >= dias_inicio");
                        });
                });

            modelBuilder.Entity("Corela15.Domain.Colocacion.Prestamo", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreadoEn")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("creado_en");

                    b.Property<string>("CreadoPor")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("creado_por");

                    b.Property<int>("Cuotas")
                        .HasColumnType("integer")
                        .HasColumnName("cuotas");

                    b.Property<bool>("DebitoSpi")
                        .HasColumnType("boolean")
                        .HasColumnName("debito_spi");

                    b.Property<decimal>("DeudaInicial")
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("deuda_inicial");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("estado");

                    b.Property<DateOnly>("FechaAdjudicacion")
                        .HasColumnType("date")
                        .HasColumnName("fecha_adjudicacion");

                    b.Property<DateOnly>("FechaVencimiento")
                        .HasColumnType("date")
                        .HasColumnName("fecha_vencimiento");

                    b.Property<int>("IdAgencia")
                        .HasColumnType("integer")
                        .HasColumnName("id_agencia");

                    b.Property<int>("IdTipoPrestamo")
                        .HasColumnType("integer")
                        .HasColumnName("id_tipo_prestamo");

                    b.Property<DateTimeOffset?>("ModificadoEn")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("modificado_en");

                    b.Property<string>("ModificadoPor")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("modificado_por");

                    b.Property<string>("Numero")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("numero");

                    b.Property<decimal>("Saldo")
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("saldo");

                    b.Property<decimal>("Tasa")
                        .HasColumnType("numeric(9,4)")
                        .HasColumnName("tasa");

                    b.Property<decimal>("Tea")
                        .HasColumnType("numeric(9,4)")
                        .HasColumnName("tea");

                    b.HasKey("Id")
                        .HasName("pk_prestamo");

                    b.HasIndex("IdAgencia")
                        .HasDatabaseName("ix_prestamo_id_agencia");

                    b.HasIndex("IdTipoPrestamo")
                        .HasDatabaseName("ix_prestamo_id_tipo_prestamo");

                    b.HasIndex("Numero")
                        .IsUnique()
                        .HasDatabaseName("ix_prestamo_numero");

                    b.ToTable("prestamo", "colocacion");
                });

            modelBuilder.Entity("Corela15.Domain.Colocacion.PrestamoCliente", b =>
                {
                    b.Property<Guid>("IdPrestamo")
                        .HasColumnType("uuid")
                        .HasColumnName("id_prestamo");

                    b.Property<Guid>("IdCliente")
                        .HasColumnType("uuid")
                        .HasColumnName("id_cliente");

                    b.Property<bool>("Activo")
                        .HasColumnType("boolean")
                        .HasColumnName("activo");

                    b.Property<bool>("Principal")
                        .HasColumnType("boolean")
                        .HasColumnName("principal");

                    b.HasKey("IdPrestamo", "IdCliente")
                        .HasName("pk_prestamo_cliente");

                    b.HasIndex("IdCliente")
                        .HasDatabaseName("ix_prestamo_cliente_id_cliente");

                    b.ToTable("prestamo_cliente", "colocacion");
                });

            modelBuilder.Entity("Corela15.Domain.Colocacion.PrestamoRubro", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<decimal>("Calculado")
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("calculado");

                    b.Property<decimal>("Cobrado")
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("cobrado");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("estado");

                    b.Property<DateOnly>("FechaFin")
                        .HasColumnType("date")
                        .HasColumnName("fecha_fin");

                    b.Property<DateOnly>("FechaInicio")
                        .HasColumnType("date")
                        .HasColumnName("fecha_inicio");

                    b.Property<Guid>("IdPrestamo")
                        .HasColumnType("uuid")
                        .HasColumnName("id_prestamo");

                    b.Property<int>("IdRubro")
                        .HasColumnType("integer")
                        .HasColumnName("id_rubro");

                    b.Property<int>("NumeroCuota")
                        .HasColumnType("integer")
                        .HasColumnName("numero_cuota");

                    b.Property<decimal>("Proyectado")
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("proyectado");

                    b.HasKey("Id")
                        .HasName("pk_prestamo_rubro");

                    b.HasIndex("IdRubro")
                        .HasDatabaseName("ix_prestamo_rubro_id_rubro");

                    b.HasIndex("IdPrestamo", "NumeroCuota", "IdRubro")
                        .IsUnique()
                        .HasDatabaseName("ix_prestamo_rubro_id_prestamo_numero_cuota_id_rubro");

                    b.ToTable("prestamo_rubro", "colocacion");
                });

            modelBuilder.Entity("Corela15.Domain.Colocacion.Rubro", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("Activo")
                        .HasColumnType("boolean")
                        .HasColumnName("activo");

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("codigo");

                    b.Property<bool>("EsCuentaPorCobrar")
                        .HasColumnType("boolean")
                        .HasColumnName("es_cuenta_por_cobrar");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("nombre");

                    b.Property<int>("OrdenDeCobro")
                        .HasColumnType("integer")
                        .HasColumnName("orden_de_cobro");

                    b.HasKey("Id")
                        .HasName("pk_rubro");

                    b.HasIndex("Codigo")
                        .IsUnique()
                        .HasDatabaseName("ix_rubro_codigo");

                    b.ToTable("rubro", "colocacion");
                });

            modelBuilder.Entity("Corela15.Domain.Colocacion.TipoVencimiento", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("Activo")
                        .HasColumnType("boolean")
                        .HasColumnName("activo");

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("codigo");

                    b.Property<bool>("EsNoDevengaInteres")
                        .HasColumnType("boolean")
                        .HasColumnName("es_no_devenga_interes");

                    b.Property<bool>("EsVencido")
                        .HasColumnType("boolean")
                        .HasColumnName("es_vencido");

                    b.Property<bool>("EsVigente")
                        .HasColumnType("boolean")
                        .HasColumnName("es_vigente");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("nombre");

                    b.HasKey("Id")
                        .HasName("pk_tipo_vencimiento");

                    b.HasIndex("Codigo")
                        .IsUnique()
                        .HasDatabaseName("ix_tipo_vencimiento_codigo");

                    b.ToTable("tipo_vencimiento", "colocacion");
                });

            modelBuilder.Entity("Corela15.Domain.Contabilidad.ComprobanteContable", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreadoEn")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("creado_en");

                    b.Property<string>("CreadoPor")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("creado_por");

                    b.Property<string>("Descripcion")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("descripcion");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("estado");

                    b.Property<DateOnly>("Fecha")
                        .HasColumnType("date")
                        .HasColumnName("fecha");

                    b.Property<int>("IdAgencia")
                        .HasColumnType("integer")
                        .HasColumnName("id_agencia");

                    b.Property<int>("IdTipoComprobante")
                        .HasColumnType("integer")
                        .HasColumnName("id_tipo_comprobante");

                    b.Property<DateTimeOffset?>("ModificadoEn")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("modificado_en");

                    b.Property<string>("ModificadoPor")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("modificado_por");

                    b.Property<long>("Numero")
                        .HasColumnType("bigint")
                        .HasColumnName("numero");

                    b.HasKey("Id")
                        .HasName("pk_comprobante_contable");

                    b.HasIndex("IdAgencia")
                        .HasDatabaseName("ix_comprobante_contable_id_agencia");

                    b.HasIndex("IdTipoComprobante", "Numero")
                        .IsUnique()
                        .HasDatabaseName("ix_comprobante_contable_id_tipo_comprobante_numero");

                    b.ToTable("comprobante_contable", "contabilidad");
                });

            modelBuilder.Entity("Corela15.Domain.Contabilidad.CuentaContable", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<bool>("Activa")
                        .HasColumnType("boolean")
                        .HasColumnName("activa");

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("codigo");

                    b.Property<DateTimeOffset>("CreadoEn")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("creado_en");

                    b.Property<string>("CreadoPor")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("creado_por");

                    b.Property<bool>("EsMayor")
                        .HasColumnType("boolean")
                        .HasColumnName("es_mayor");

                    b.Property<string>("Grupo")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("grupo");

                    b.Property<Guid?>("IdCuentaPadre")
                        .HasColumnType("uuid")
                        .HasColumnName("id_cuenta_padre");

                    b.Property<DateTimeOffset?>("ModificadoEn")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("modificado_en");

                    b.Property<string>("ModificadoPor")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("modificado_por");

                    b.Property<string>("Naturaleza")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("naturaleza");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("nombre");

                    b.HasKey("Id")
                        .HasName("pk_cuenta_contable");

                    b.HasIndex("Codigo")
                        .IsUnique()
                        .HasDatabaseName("ix_cuenta_contable_codigo");

                    b.HasIndex("IdCuentaPadre")
                        .HasDatabaseName("ix_cuenta_contable_id_cuenta_padre");

                    b.ToTable("cuenta_contable", "contabilidad");
                });

            modelBuilder.Entity("Corela15.Domain.Contabilidad.MovimientoComprobanteContable", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<decimal>("Credito")
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("credito");

                    b.Property<decimal>("Debito")
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("debito");

                    b.Property<string>("Descripcion")
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)")
                        .HasColumnName("descripcion");

                    b.Property<Guid>("IdComprobante")
                        .HasColumnType("uuid")
                        .HasColumnName("id_comprobante");

                    b.Property<Guid>("IdCuentaContable")
                        .HasColumnType("uuid")
                        .HasColumnName("id_cuenta_contable");

                    b.Property<int>("NumeroLinea")
                        .HasColumnType("integer")
                        .HasColumnName("numero_linea");

                    b.HasKey("Id")
                        .HasName("pk_movimiento_comprobante_contable");

                    b.HasIndex("IdCuentaContable")
                        .HasDatabaseName("ix_movimiento_comprobante_contable_id_cuenta_contable");

                    b.HasIndex("IdComprobante", "NumeroLinea")
                        .IsUnique()
                        .HasDatabaseName("ix_movimiento_comprobante_contable_id_comprobante_numero_linea");

                    b.ToTable("movimiento_comprobante_contable", "contabilidad", t =>
                        {
                            t.HasCheckConstraint("ck_movimiento_debito_o_credito", "(debito = 0 OR credito = 0) AND (debito + credito) > 0");
                        });
                });

            modelBuilder.Entity("Corela15.Domain.Contabilidad.SaldoContable", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("IdCuentaContable")
                        .HasColumnType("uuid")
                        .HasColumnName("id_cuenta_contable");

                    b.Property<DateOnly>("Periodo")
                        .HasColumnType("date")
                        .HasColumnName("periodo");

                    b.Property<decimal>("SaldoFinal")
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("saldo_final");

                    b.Property<decimal>("TotalCreditos")
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("total_creditos");

                    b.Property<decimal>("TotalDebitos")
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("total_debitos");

                    b.HasKey("Id")
                        .HasName("pk_saldo_contable");

                    b.HasIndex("IdCuentaContable", "Periodo")
                        .IsUnique()
                        .HasDatabaseName("ix_saldo_contable_id_cuenta_contable_periodo");

                    b.ToTable("saldo_contable", "contabilidad");
                });

            modelBuilder.Entity("Corela15.Domain.Contabilidad.TipoComprobanteContable", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("codigo");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("nombre");

                    b.HasKey("Id")
                        .HasName("pk_tipo_comprobante_contable");

                    b.HasIndex("Codigo")
                        .IsUnique()
                        .HasDatabaseName("ix_tipo_comprobante_contable_codigo");

                    b.ToTable("tipo_comprobante_contable", "contabilidad");
                });

            modelBuilder.Entity("Corela15.Domain.Credito.SolicitudPrestamo", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreadoEn")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("creado_en");

                    b.Property<string>("CreadoPor")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("creado_por");

                    b.Property<int>("Cuotas")
                        .HasColumnType("integer")
                        .HasColumnName("cuotas");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("estado");

                    b.Property<DateOnly>("FechaSolicitud")
                        .HasColumnType("date")
                        .HasColumnName("fecha_solicitud");

                    b.Property<int>("IdAgencia")
                        .HasColumnType("integer")
                        .HasColumnName("id_agencia");

                    b.Property<Guid>("IdCliente")
                        .HasColumnType("uuid")
                        .HasColumnName("id_cliente");

                    b.Property<int>("IdTipoPrestamo")
                        .HasColumnType("integer")
                        .HasColumnName("id_tipo_prestamo");

                    b.Property<DateTimeOffset?>("ModificadoEn")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("modificado_en");

                    b.Property<string>("ModificadoPor")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("modificado_por");

                    b.Property<decimal?>("MontoAprobado")
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("monto_aprobado");

                    b.Property<decimal>("MontoSolicitado")
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("monto_solicitado");

                    b.Property<string>("Numero")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("numero");

                    b.HasKey("Id")
                        .HasName("pk_solicitud_prestamo");

                    b.HasIndex("IdAgencia")
                        .HasDatabaseName("ix_solicitud_prestamo_id_agencia");

                    b.HasIndex("IdCliente")
                        .HasDatabaseName("ix_solicitud_prestamo_id_cliente");

                    b.HasIndex("IdTipoPrestamo")
                        .HasDatabaseName("ix_solicitud_prestamo_id_tipo_prestamo");

                    b.HasIndex("Numero")
                        .IsUnique()
                        .HasDatabaseName("ix_solicitud_prestamo_numero");

                    b.ToTable("solicitud_prestamo", "credito");
                });

            modelBuilder.Entity("Corela15.Domain.Credito.TipoPrestamo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("Activo")
                        .HasColumnType("boolean")
                        .HasColumnName("activo");

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("codigo");

                    b.Property<decimal>("MontoMaximo")
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("monto_maximo");

                    b.Property<decimal>("MontoMinimo")
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("monto_minimo");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("nombre");

                    b.Property<int>("PlazoMaximoDias")
                        .HasColumnType("integer")
                        .HasColumnName("plazo_maximo_dias");

                    b.Property<int>("PlazoMinimoDias")
                        .HasColumnType("integer")
                        .HasColumnName("plazo_minimo_dias");

                    b.HasKey("Id")
                        .HasName("pk_tipo_prestamo");

                    b.HasIndex("Codigo")
                        .IsUnique()
                        .HasDatabaseName("ix_tipo_prestamo_codigo");

                    b.ToTable("tipo_prestamo", "credito");
                });

            modelBuilder.Entity("Corela15.Domain.General.Agencia", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("Activa")
                        .HasColumnType("boolean")
                        .HasColumnName("activa");

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("codigo");

                    b.Property<bool>("EsOperativa")
                        .HasColumnType("boolean")
                        .HasColumnName("es_operativa");

                    b.Property<int>("IdEmpresa")
                        .HasColumnType("integer")
                        .HasColumnName("id_empresa");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("nombre");

                    b.HasKey("Id")
                        .HasName("pk_agencia");

                    b.HasIndex("IdEmpresa", "Codigo")
                        .IsUnique()
                        .HasDatabaseName("ix_agencia_id_empresa_codigo");

                    b.ToTable("agencia", "general");
                });

            modelBuilder.Entity("Corela15.Domain.General.Empresa", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("codigo");

                    b.Property<int>("IdMoneda")
                        .HasColumnType("integer")
                        .HasColumnName("id_moneda");

                    b.Property<int>("IdPais")
                        .HasColumnType("integer")
                        .HasColumnName("id_pais");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("nombre");

                    b.Property<string>("Ruc")
                        .IsRequired()
                        .HasMaxLength(13)
                        .HasColumnType("character varying(13)")
                        .HasColumnName("ruc");

                    b.HasKey("Id")
                        .HasName("pk_empresa");

                    b.HasIndex("IdMoneda")
                        .HasDatabaseName("ix_empresa_id_moneda");

                    b.HasIndex("IdPais")
                        .HasDatabaseName("ix_empresa_id_pais");

                    b.HasIndex("Ruc")
                        .IsUnique()
                        .HasDatabaseName("ix_empresa_ruc");

                    b.ToTable("empresa", "general");
                });

            modelBuilder.Entity("Corela15.Domain.General.Moneda", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("character varying(3)")
                        .HasColumnName("codigo");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("nombre");

                    b.Property<string>("Simbolo")
                        .IsRequired()
                        .HasMaxLength(5)
                        .HasColumnType("character varying(5)")
                        .HasColumnName("simbolo");

                    b.HasKey("Id")
                        .HasName("pk_moneda");

                    b.HasIndex("Codigo")
                        .IsUnique()
                        .HasDatabaseName("ix_moneda_codigo");

                    b.ToTable("moneda", "general");
                });

            modelBuilder.Entity("Corela15.Domain.General.Pais", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("character varying(3)")
                        .HasColumnName("codigo");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("nombre");

                    b.HasKey("Id")
                        .HasName("pk_pais");

                    b.HasIndex("Codigo")
                        .IsUnique()
                        .HasDatabaseName("ix_pais_codigo");

                    b.ToTable("pais", "general");
                });

            modelBuilder.Entity("Corela15.Domain.General.TipoIdentificacion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("codigo");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("nombre");

                    b.HasKey("Id")
                        .HasName("pk_tipo_identificacion");

                    b.HasIndex("Codigo")
                        .IsUnique()
                        .HasDatabaseName("ix_tipo_identificacion_codigo");

                    b.ToTable("tipo_identificacion", "general");
                });

            modelBuilder.Entity("Corela15.Domain.Inversion.Deposito", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("codigo");

                    b.Property<DateTimeOffset>("CreadoEn")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("creado_en");

                    b.Property<string>("CreadoPor")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("creado_por");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("estado");

                    b.Property<DateOnly>("FechaCreacion")
                        .HasColumnType("date")
                        .HasColumnName("fecha_creacion");

                    b.Property<DateOnly>("FechaVencimiento")
                        .HasColumnType("date")
                        .HasColumnName("fecha_vencimiento");

                    b.Property<int>("IdAgencia")
                        .HasColumnType("integer")
                        .HasColumnName("id_agencia");

                    b.Property<DateTimeOffset?>("ModificadoEn")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("modificado_en");

                    b.Property<string>("ModificadoPor")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("modificado_por");

                    b.Property<decimal>("Monto")
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("monto");

                    b.Property<bool>("PagoPeriodicoInteres")
                        .HasColumnType("boolean")
                        .HasColumnName("pago_periodico_interes");

                    b.Property<int>("PlazoDias")
                        .HasColumnType("integer")
                        .HasColumnName("plazo_dias");

                    b.Property<decimal>("Tasa")
                        .HasColumnType("numeric(9,4)")
                        .HasColumnName("tasa");

                    b.Property<decimal>("VariacionTasa")
                        .HasColumnType("numeric(9,4)")
                        .HasColumnName("variacion_tasa");

                    b.HasKey("Id")
                        .HasName("pk_deposito");

                    b.HasIndex("Codigo")
                        .IsUnique()
                        .HasDatabaseName("ix_deposito_codigo");

                    b.HasIndex("IdAgencia")
                        .HasDatabaseName("ix_deposito_id_agencia");

                    b.ToTable("deposito", "inversion");
                });

            modelBuilder.Entity("Corela15.Domain.Inversion.DepositoCliente", b =>
                {
                    b.Property<Guid>("IdDeposito")
                        .HasColumnType("uuid")
                        .HasColumnName("id_deposito");

                    b.Property<Guid>("IdCliente")
                        .HasColumnType("uuid")
                        .HasColumnName("id_cliente");

                    b.Property<bool>("Activo")
                        .HasColumnType("boolean")
                        .HasColumnName("activo");

                    b.Property<bool>("Principal")
                        .HasColumnType("boolean")
                        .HasColumnName("principal");

                    b.HasKey("IdDeposito", "IdCliente")
                        .HasName("pk_deposito_cliente");

                    b.HasIndex("IdCliente")
                        .HasDatabaseName("ix_deposito_cliente_id_cliente");

                    b.ToTable("deposito_cliente", "inversion");
                });

            modelBuilder.Entity("Corela15.Domain.Inversion.DepositoRenovacion", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateOnly>("FechaRenovacion")
                        .HasColumnType("date")
                        .HasColumnName("fecha_renovacion");

                    b.Property<Guid>("IdDepositoDestino")
                        .HasColumnType("uuid")
                        .HasColumnName("id_deposito_destino");

                    b.Property<Guid>("IdDepositoOrigen")
                        .HasColumnType("uuid")
                        .HasColumnName("id_deposito_origen");

                    b.Property<decimal>("Valor")
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("valor");

                    b.Property<decimal>("ValorIncremento")
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("valor_incremento");

                    b.HasKey("Id")
                        .HasName("pk_deposito_renovacion");

                    b.HasIndex("IdDepositoDestino")
                        .HasDatabaseName("ix_deposito_renovacion_id_deposito_destino");

                    b.HasIndex("IdDepositoOrigen")
                        .HasDatabaseName("ix_deposito_renovacion_id_deposito_origen");

                    b.ToTable("deposito_renovacion", "inversion");
                });

            modelBuilder.Entity("Corela15.Domain.Inversion.ItemPlazoTasa", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<bool>("Activo")
                        .HasColumnType("boolean")
                        .HasColumnName("activo");

                    b.Property<DateOnly>("FechaVigenciaDesde")
                        .HasColumnType("date")
                        .HasColumnName("fecha_vigencia_desde");

                    b.Property<decimal?>("MontoMax")
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("monto_max");

                    b.Property<decimal>("MontoMin")
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("monto_min");

                    b.Property<int>("PlazoDiasMax")
                        .HasColumnType("integer")
                        .HasColumnName("plazo_dias_max");

                    b.Property<int>("PlazoDiasMin")
                        .HasColumnType("integer")
                        .HasColumnName("plazo_dias_min");

                    b.Property<decimal>("Tasa")
                        .HasColumnType("numeric(9,4)")
                        .HasColumnName("tasa");

                    b.Property<string>("TipoPersona")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("tipo_persona");

                    b.HasKey("Id")
                        .HasName("pk_item_plazo_tasa");

                    b.ToTable("item_plazo_tasa", "inversion");
                });

            modelBuilder.Entity("Corela15.Domain.Seguridad.AccionIngresoUsuario", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityAlwaysColumn(b.Property<long>("Id"));

                    b.Property<string>("Detalle")
                        .HasColumnType("text")
                        .HasColumnName("detalle");

                    b.Property<string>("DireccionIp")
                        .HasMaxLength(45)
                        .HasColumnType("character varying(45)")
                        .HasColumnName("direccion_ip");

                    b.Property<bool>("Exitoso")
                        .HasColumnType("boolean")
                        .HasColumnName("exitoso");

                    b.Property<DateTimeOffset>("FechaHora")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fecha_hora");

                    b.Property<Guid>("IdUsuario")
                        .HasColumnType("uuid")
                        .HasColumnName("id_usuario");

                    b.HasKey("Id")
                        .HasName("pk_accion_ingreso_usuario");

                    b.HasIndex("FechaHora")
                        .HasDatabaseName("ix_accion_ingreso_usuario_fecha_hora");

                    b.HasIndex("IdUsuario")
                        .HasDatabaseName("ix_accion_ingreso_usuario_id_usuario");

                    b.ToTable("accion_ingreso_usuario", "seguridad");
                });

            modelBuilder.Entity("Corela15.Domain.Seguridad.Rol", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("Nivel")
                        .HasColumnType("integer")
                        .HasColumnName("nivel");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("nombre");

                    b.HasKey("Id")
                        .HasName("pk_rol");

                    b.HasIndex("Nombre")
                        .IsUnique()
                        .HasDatabaseName("ix_rol_nombre");

                    b.ToTable("rol", "seguridad");
                });

            modelBuilder.Entity("Corela15.Domain.Seguridad.Usuario", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<bool>("Activo")
                        .HasColumnType("boolean")
                        .HasColumnName("activo");

                    b.Property<DateTimeOffset>("CreadoEn")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("creado_en");

                    b.Property<string>("CreadoPor")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("creado_por");

                    b.Property<string>("HashContrasena")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("hash_contrasena");

                    b.Property<int>("IdAgencia")
                        .HasColumnType("integer")
                        .HasColumnName("id_agencia");

                    b.Property<Guid?>("IdPersona")
                        .HasColumnType("uuid")
                        .HasColumnName("id_persona");

                    b.Property<DateTimeOffset?>("ModificadoEn")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("modificado_en");

                    b.Property<string>("ModificadoPor")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("modificado_por");

                    b.Property<string>("NombreUsuario")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("nombre_usuario");

                    b.Property<bool>("PuedeIngresarSistema")
                        .HasColumnType("boolean")
                        .HasColumnName("puede_ingresar_sistema");

                    b.Property<bool>("TieneBloqueo")
                        .HasColumnType("boolean")
                        .HasColumnName("tiene_bloqueo");

                    b.HasKey("Id")
                        .HasName("pk_usuario");

                    b.HasIndex("IdAgencia")
                        .HasDatabaseName("ix_usuario_id_agencia");

                    b.HasIndex("IdPersona")
                        .HasDatabaseName("ix_usuario_id_persona");

                    b.HasIndex("NombreUsuario")
                        .IsUnique()
                        .HasDatabaseName("ix_usuario_nombre_usuario");

                    b.ToTable("usuario", "seguridad");
                });

            modelBuilder.Entity("Corela15.Domain.Seguridad.UsuarioRol", b =>
                {
                    b.Property<Guid>("IdUsuario")
                        .HasColumnType("uuid")
                        .HasColumnName("id_usuario");

                    b.Property<int>("IdRol")
                        .HasColumnType("integer")
                        .HasColumnName("id_rol");

                    b.Property<bool>("Activo")
                        .HasColumnType("boolean")
                        .HasColumnName("activo");

                    b.Property<DateTimeOffset>("AsignadoEn")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("asignado_en");

                    b.HasKey("IdUsuario", "IdRol")
                        .HasName("pk_usuario_rol");

                    b.HasIndex("IdRol")
                        .HasDatabaseName("ix_usuario_rol_id_rol");

                    b.ToTable("usuario_rol", "seguridad");
                });

            modelBuilder.Entity("Corela15.Domain.Sujeto.Persona", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<decimal?>("Activos")
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("activos");

                    b.Property<string>("Barrio")
                        .HasColumnType("text")
                        .HasColumnName("barrio");

                    b.Property<string>("CallePrincipal")
                        .HasColumnType("text")
                        .HasColumnName("calle_principal");

                    b.Property<DateTimeOffset>("CreadoEn")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("creado_en");

                    b.Property<string>("CreadoPor")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("creado_por");

                    b.Property<decimal?>("Egresos")
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("egresos");

                    b.Property<string>("Email")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("email");

                    b.Property<int?>("IdActividadEconomica")
                        .HasColumnType("integer")
                        .HasColumnName("id_actividad_economica");

                    b.Property<int?>("IdPais")
                        .HasColumnType("integer")
                        .HasColumnName("id_pais");

                    b.Property<int>("IdTipoIdentificacion")
                        .HasColumnType("integer")
                        .HasColumnName("id_tipo_identificacion");

                    b.Property<string>("Identificacion")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("identificacion");

                    b.Property<decimal?>("Ingresos")
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("ingresos");

                    b.Property<DateTimeOffset?>("ModificadoEn")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("modificado_en");

                    b.Property<string>("ModificadoPor")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("modificado_por");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)")
                        .HasColumnName("nombre");

                    b.Property<string>("NumeroCasa")
                        .HasColumnType("text")
                        .HasColumnName("numero_casa");

                    b.Property<decimal?>("Pasivos")
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("pasivos");

                    b.HasKey("Id")
                        .HasName("pk_persona");

                    b.HasIndex("IdPais")
                        .HasDatabaseName("ix_persona_id_pais");

                    b.HasIndex("IdTipoIdentificacion", "Identificacion")
                        .IsUnique()
                        .HasDatabaseName("ix_persona_id_tipo_identificacion_identificacion");

                    b.ToTable("persona", "sujeto");
                });

            modelBuilder.Entity("Corela15.Domain.Sujeto.PersonaJuridica", b =>
                {
                    b.Property<Guid>("IdPersona")
                        .HasColumnType("uuid")
                        .HasColumnName("id_persona");

                    b.Property<bool>("EsGrupo")
                        .HasColumnType("boolean")
                        .HasColumnName("es_grupo");

                    b.Property<bool>("EsInstitucionBancaria")
                        .HasColumnType("boolean")
                        .HasColumnName("es_institucion_bancaria");

                    b.Property<bool>("EsPublica")
                        .HasColumnType("boolean")
                        .HasColumnName("es_publica");

                    b.Property<DateOnly>("FechaCreacion")
                        .HasColumnType("date")
                        .HasColumnName("fecha_creacion");

                    b.Property<int?>("PaisConstitucion")
                        .HasColumnType("integer")
                        .HasColumnName("pais_constitucion");

                    b.Property<string>("RazonSocial")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)")
                        .HasColumnName("razon_social");

                    b.HasKey("IdPersona")
                        .HasName("pk_persona_juridica");

                    b.ToTable("persona_juridica", "sujeto");
                });

            modelBuilder.Entity("Corela15.Domain.Sujeto.PersonaNatural", b =>
                {
                    b.Property<Guid>("IdPersona")
                        .HasColumnType("uuid")
                        .HasColumnName("id_persona");

                    b.Property<string>("ApellidoMaterno")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("apellido_materno");

                    b.Property<string>("ApellidoPaterno")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("apellido_paterno");

                    b.Property<bool>("EsMasculino")
                        .HasColumnType("boolean")
                        .HasColumnName("es_masculino");

                    b.Property<bool>("EsPep")
                        .HasColumnType("boolean")
                        .HasColumnName("es_pep");

                    b.Property<DateOnly>("FechaNacimiento")
                        .HasColumnType("date")
                        .HasColumnName("fecha_nacimiento");

                    b.Property<string>("PrimerNombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("primer_nombre");

                    b.Property<string>("SegundoNombre")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("segundo_nombre");

                    b.HasKey("IdPersona")
                        .HasName("pk_persona_natural");

                    b.ToTable("persona_natural", "sujeto");
                });

            modelBuilder.Entity("Corela15.Domain.Ahorros.Cuenta", b =>
                {
                    b.HasOne("Corela15.Domain.General.Agencia", "Agencia")
                        .WithMany()
                        .HasForeignKey("IdAgencia")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_cuenta_agencia_id_agencia");

                    b.HasOne("Corela15.Domain.Ahorros.TipoCuenta", "TipoCuenta")
                        .WithMany()
                        .HasForeignKey("IdTipoCuenta")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_cuenta_tipos_cuenta_id_tipo_cuenta");

                    b.Navigation("Agencia");

                    b.Navigation("TipoCuenta");
                });

            modelBuilder.Entity("Corela15.Domain.Ahorros.CuentaCliente", b =>
                {
                    b.HasOne("Corela15.Domain.Clientes.Cliente", "Cliente")
                        .WithMany()
                        .HasForeignKey("IdCliente")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_cuenta_cliente_cliente_id_cliente");

                    b.HasOne("Corela15.Domain.Ahorros.Cuenta", "Cuenta")
                        .WithMany()
                        .HasForeignKey("IdCuenta")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_cuenta_cliente_cuentas_id_cuenta");

                    b.Navigation("Cliente");

                    b.Navigation("Cuenta");
                });

            modelBuilder.Entity("Corela15.Domain.Ahorros.CuentaItemSaldo", b =>
                {
                    b.HasOne("Corela15.Domain.Ahorros.Cuenta", "Cuenta")
                        .WithMany()
                        .HasForeignKey("IdCuenta")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_cuenta_item_saldo_cuenta_id_cuenta");

                    b.HasOne("Corela15.Domain.Ahorros.ItemSaldo", "ItemSaldo")
                        .WithMany()
                        .HasForeignKey("IdItemSaldo")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_cuenta_item_saldo_items_saldo_id_item_saldo");

                    b.Navigation("Cuenta");

                    b.Navigation("ItemSaldo");
                });

            modelBuilder.Entity("Corela15.Domain.Ahorros.TipoCuentaItemSaldo", b =>
                {
                    b.HasOne("Corela15.Domain.Ahorros.ItemSaldo", "ItemSaldo")
                        .WithMany()
                        .HasForeignKey("IdItemSaldo")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_tipo_cuenta_item_saldo_item_saldo_id_item_saldo");

                    b.HasOne("Corela15.Domain.Ahorros.TipoCuenta", "TipoCuenta")
                        .WithMany()
                        .HasForeignKey("IdTipoCuenta")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_tipo_cuenta_item_saldo_tipo_cuenta_id_tipo_cuenta");

                    b.Navigation("ItemSaldo");

                    b.Navigation("TipoCuenta");
                });

            modelBuilder.Entity("Corela15.Domain.Clientes.Cliente", b =>
                {
                    b.HasOne("Corela15.Domain.General.Agencia", "Agencia")
                        .WithMany()
                        .HasForeignKey("IdAgencia")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_cliente_agencia_id_agencia");

                    b.HasOne("Corela15.Domain.Sujeto.Persona", "Persona")
                        .WithMany()
                        .HasForeignKey("IdPersona")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_cliente_personas_id_persona");

                    b.Navigation("Agencia");

                    b.Navigation("Persona");
                });

            modelBuilder.Entity("Corela15.Domain.Colocacion.ClasificacionCartera", b =>
                {
                    b.HasOne("Corela15.Domain.Contabilidad.CuentaContable", "CuentaContable")
                        .WithMany()
                        .HasForeignKey("IdCuentaContable")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_clasificacion_cartera_cuentas_contables_id_cuenta_contable");

                    b.HasOne("Corela15.Domain.Colocacion.TipoVencimiento", "TipoVencimiento")
                        .WithMany()
                        .HasForeignKey("IdTipoVencimiento")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_clasificacion_cartera_tipos_vencimiento_id_tipo_vencimiento");

                    b.Navigation("CuentaContable");

                    b.Navigation("TipoVencimiento");
                });

            modelBuilder.Entity("Corela15.Domain.Colocacion.Prestamo", b =>
                {
                    b.HasOne("Corela15.Domain.General.Agencia", "Agencia")
                        .WithMany()
                        .HasForeignKey("IdAgencia")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_prestamo_agencia_id_agencia");

                    b.HasOne("Corela15.Domain.Credito.TipoPrestamo", "TipoPrestamo")
                        .WithMany()
                        .HasForeignKey("IdTipoPrestamo")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_prestamo_tipos_prestamo_id_tipo_prestamo");

                    b.Navigation("Agencia");

                    b.Navigation("TipoPrestamo");
                });

            modelBuilder.Entity("Corela15.Domain.Colocacion.PrestamoCliente", b =>
                {
                    b.HasOne("Corela15.Domain.Clientes.Cliente", "Cliente")
                        .WithMany()
                        .HasForeignKey("IdCliente")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_prestamo_cliente_cliente_id_cliente");

                    b.HasOne("Corela15.Domain.Colocacion.Prestamo", "Prestamo")
                        .WithMany()
                        .HasForeignKey("IdPrestamo")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_prestamo_cliente_prestamos_id_prestamo");

                    b.Navigation("Cliente");

                    b.Navigation("Prestamo");
                });

            modelBuilder.Entity("Corela15.Domain.Colocacion.PrestamoRubro", b =>
                {
                    b.HasOne("Corela15.Domain.Colocacion.Prestamo", "Prestamo")
                        .WithMany()
                        .HasForeignKey("IdPrestamo")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_prestamo_rubro_prestamo_id_prestamo");

                    b.HasOne("Corela15.Domain.Colocacion.Rubro", "Rubro")
                        .WithMany()
                        .HasForeignKey("IdRubro")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_prestamo_rubro_rubros_id_rubro");

                    b.Navigation("Prestamo");

                    b.Navigation("Rubro");
                });

            modelBuilder.Entity("Corela15.Domain.Contabilidad.ComprobanteContable", b =>
                {
                    b.HasOne("Corela15.Domain.General.Agencia", "Agencia")
                        .WithMany()
                        .HasForeignKey("IdAgencia")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_comprobante_contable_agencia_id_agencia");

                    b.HasOne("Corela15.Domain.Contabilidad.TipoComprobanteContable", "TipoComprobante")
                        .WithMany()
                        .HasForeignKey("IdTipoComprobante")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_comprobante_contable_tipos_comprobante_contable_id_tipo_com");

                    b.Navigation("Agencia");

                    b.Navigation("TipoComprobante");
                });

            modelBuilder.Entity("Corela15.Domain.Contabilidad.CuentaContable", b =>
                {
                    b.HasOne("Corela15.Domain.Contabilidad.CuentaContable", "CuentaPadre")
                        .WithMany()
                        .HasForeignKey("IdCuentaPadre")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_cuenta_contable_cuenta_contable_id_cuenta_padre");

                    b.Navigation("CuentaPadre");
                });

            modelBuilder.Entity("Corela15.Domain.Contabilidad.MovimientoComprobanteContable", b =>
                {
                    b.HasOne("Corela15.Domain.Contabilidad.ComprobanteContable", "Comprobante")
                        .WithMany("Movimientos")
                        .HasForeignKey("IdComprobante")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_movimiento_comprobante_contable_comprobante_contable_id_com");

                    b.HasOne("Corela15.Domain.Contabilidad.CuentaContable", "CuentaContable")
                        .WithMany()
                        .HasForeignKey("IdCuentaContable")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_movimiento_comprobante_contable_cuenta_contable_id_cuenta_c");

                    b.Navigation("Comprobante");

                    b.Navigation("CuentaContable");
                });

            modelBuilder.Entity("Corela15.Domain.Contabilidad.SaldoContable", b =>
                {
                    b.HasOne("Corela15.Domain.Contabilidad.CuentaContable", "CuentaContable")
                        .WithMany()
                        .HasForeignKey("IdCuentaContable")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_saldo_contable_cuenta_contable_id_cuenta_contable");

                    b.Navigation("CuentaContable");
                });

            modelBuilder.Entity("Corela15.Domain.Credito.SolicitudPrestamo", b =>
                {
                    b.HasOne("Corela15.Domain.General.Agencia", "Agencia")
                        .WithMany()
                        .HasForeignKey("IdAgencia")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_solicitud_prestamo_agencia_id_agencia");

                    b.HasOne("Corela15.Domain.Clientes.Cliente", "Cliente")
                        .WithMany()
                        .HasForeignKey("IdCliente")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_solicitud_prestamo_cliente_id_cliente");

                    b.HasOne("Corela15.Domain.Credito.TipoPrestamo", "TipoPrestamo")
                        .WithMany()
                        .HasForeignKey("IdTipoPrestamo")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_solicitud_prestamo_tipos_prestamo_id_tipo_prestamo");

                    b.Navigation("Agencia");

                    b.Navigation("Cliente");

                    b.Navigation("TipoPrestamo");
                });

            modelBuilder.Entity("Corela15.Domain.General.Agencia", b =>
                {
                    b.HasOne("Corela15.Domain.General.Empresa", "Empresa")
                        .WithMany()
                        .HasForeignKey("IdEmpresa")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_agencia_empresas_id_empresa");

                    b.Navigation("Empresa");
                });

            modelBuilder.Entity("Corela15.Domain.General.Empresa", b =>
                {
                    b.HasOne("Corela15.Domain.General.Moneda", "Moneda")
                        .WithMany()
                        .HasForeignKey("IdMoneda")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_empresa_monedas_id_moneda");

                    b.HasOne("Corela15.Domain.General.Pais", "Pais")
                        .WithMany()
                        .HasForeignKey("IdPais")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_empresa_paises_id_pais");

                    b.Navigation("Moneda");

                    b.Navigation("Pais");
                });

            modelBuilder.Entity("Corela15.Domain.Inversion.Deposito", b =>
                {
                    b.HasOne("Corela15.Domain.General.Agencia", "Agencia")
                        .WithMany()
                        .HasForeignKey("IdAgencia")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_deposito_agencia_id_agencia");

                    b.Navigation("Agencia");
                });

            modelBuilder.Entity("Corela15.Domain.Inversion.DepositoCliente", b =>
                {
                    b.HasOne("Corela15.Domain.Clientes.Cliente", "Cliente")
                        .WithMany()
                        .HasForeignKey("IdCliente")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_deposito_cliente_cliente_id_cliente");

                    b.HasOne("Corela15.Domain.Inversion.Deposito", "Deposito")
                        .WithMany()
                        .HasForeignKey("IdDeposito")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_deposito_cliente_depositos_id_deposito");

                    b.Navigation("Cliente");

                    b.Navigation("Deposito");
                });

            modelBuilder.Entity("Corela15.Domain.Inversion.DepositoRenovacion", b =>
                {
                    b.HasOne("Corela15.Domain.Inversion.Deposito", "DepositoDestino")
                        .WithMany()
                        .HasForeignKey("IdDepositoDestino")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_deposito_renovacion_deposito_id_deposito_destino");

                    b.HasOne("Corela15.Domain.Inversion.Deposito", "DepositoOrigen")
                        .WithMany()
                        .HasForeignKey("IdDepositoOrigen")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_deposito_renovacion_deposito_id_deposito_origen");

                    b.Navigation("DepositoDestino");

                    b.Navigation("DepositoOrigen");
                });

            modelBuilder.Entity("Corela15.Domain.Seguridad.AccionIngresoUsuario", b =>
                {
                    b.HasOne("Corela15.Domain.Seguridad.Usuario", "Usuario")
                        .WithMany()
                        .HasForeignKey("IdUsuario")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_accion_ingreso_usuario_usuarios_id_usuario");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("Corela15.Domain.Seguridad.Usuario", b =>
                {
                    b.HasOne("Corela15.Domain.General.Agencia", "Agencia")
                        .WithMany()
                        .HasForeignKey("IdAgencia")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_usuario_agencia_id_agencia");

                    b.HasOne("Corela15.Domain.Sujeto.Persona", "Persona")
                        .WithMany()
                        .HasForeignKey("IdPersona")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_usuario_persona_id_persona");

                    b.Navigation("Agencia");

                    b.Navigation("Persona");
                });

            modelBuilder.Entity("Corela15.Domain.Seguridad.UsuarioRol", b =>
                {
                    b.HasOne("Corela15.Domain.Seguridad.Rol", "Rol")
                        .WithMany("UsuarioRoles")
                        .HasForeignKey("IdRol")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_usuario_rol_rol_id_rol");

                    b.HasOne("Corela15.Domain.Seguridad.Usuario", "Usuario")
                        .WithMany("UsuarioRoles")
                        .HasForeignKey("IdUsuario")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_usuario_rol_usuario_id_usuario");

                    b.Navigation("Rol");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("Corela15.Domain.Sujeto.Persona", b =>
                {
                    b.HasOne("Corela15.Domain.General.Pais", "Pais")
                        .WithMany()
                        .HasForeignKey("IdPais")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_persona_pais_id_pais");

                    b.HasOne("Corela15.Domain.General.TipoIdentificacion", "TipoIdentificacion")
                        .WithMany()
                        .HasForeignKey("IdTipoIdentificacion")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_persona_tipos_identificacion_id_tipo_identificacion");

                    b.Navigation("Pais");

                    b.Navigation("TipoIdentificacion");
                });

            modelBuilder.Entity("Corela15.Domain.Sujeto.PersonaJuridica", b =>
                {
                    b.HasOne("Corela15.Domain.Sujeto.Persona", "Persona")
                        .WithOne("PersonaJuridica")
                        .HasForeignKey("Corela15.Domain.Sujeto.PersonaJuridica", "IdPersona")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_persona_juridica_persona_id_persona");

                    b.Navigation("Persona");
                });

            modelBuilder.Entity("Corela15.Domain.Sujeto.PersonaNatural", b =>
                {
                    b.HasOne("Corela15.Domain.Sujeto.Persona", "Persona")
                        .WithOne("PersonaNatural")
                        .HasForeignKey("Corela15.Domain.Sujeto.PersonaNatural", "IdPersona")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_persona_natural_persona_id_persona");

                    b.Navigation("Persona");
                });

            modelBuilder.Entity("Corela15.Domain.Contabilidad.ComprobanteContable", b =>
                {
                    b.Navigation("Movimientos");
                });

            modelBuilder.Entity("Corela15.Domain.Seguridad.Rol", b =>
                {
                    b.Navigation("UsuarioRoles");
                });

            modelBuilder.Entity("Corela15.Domain.Seguridad.Usuario", b =>
                {
                    b.Navigation("UsuarioRoles");
                });

            modelBuilder.Entity("Corela15.Domain.Sujeto.Persona", b =>
                {
                    b.Navigation("PersonaJuridica");

                    b.Navigation("PersonaNatural");
                });
#pragma warning restore 612, 618
        }
    }
}
