INSERT INTO sujeto.profesion (codigo, nombre, activo) VALUES ('0124', 'LIC TURISMO Y HOTELE', true);
INSERT INTO sujeto.profesion (codigo, nombre, activo) VALUES ('093', 'MARMOLERO', true);
INSERT INTO sujeto.profesion (codigo, nombre, activo) VALUES ('098', 'TEC SUP SECRET EJEC', true);
INSERT INTO sujeto.profesion (codigo, nombre, activo) VALUES ('1', 'JORNALERO', true);
INSERT INTO sujeto.profesion (codigo, nombre, activo) VALUES ('10', 'ADMINISTRADOR', true);
INSERT INTO sujeto.profesion (codigo, nombre, activo) VALUES ('100', 'BISELADOR', true);
INSERT INTO sujeto.profesion (codigo, nombre, activo) VALUES ('1001', 'ASTROFISICO', true);
INSERT INTO sujeto.profesion (codigo, nombre, activo) VALUES ('101', 'BLANQUEADOR', true);
INSERT INTO sujeto.profesion (codigo, nombre, activo) VALUES ('102', 'BODEGUERO', true);
INSERT INTO sujeto.profesion (codigo, nombre, activo) VALUES ('103', 'BOLETERO', true);
INSERT INTO sujeto.profesion (codigo, nombre, activo) VALUES ('104', 'BOMBERO', true);
INSERT INTO sujeto.profesion (codigo, nombre, activo) VALUES ('105', 'BORDADOR', true);
INSERT INTO sujeto.profesion (codigo, nombre, activo) VALUES ('106', 'BOTANICO', true);
INSERT INTO sujeto.profesion (codigo, nombre, activo) VALUES ('107', 'BOTICARIO', true);
INSERT INTO sujeto.profesion (codigo, nombre, activo) VALUES ('108', 'BOXEADOR', true);
INSERT INTO sujeto.profesion (codigo, nombre, activo) VALUES ('109', 'BRACERO', true);
INSERT INTO sujeto.profesion (codigo, nombre, activo) VALUES ('11', 'ADMINISTRADOR AGRICOLA', true);
INSERT INTO sujeto.profesion (codigo, nombre, activo) VALUES ('110', 'BREQUERO', true);
INSERT INTO sujeto.profesion (codigo, nombre, activo) VALUES ('111', 'BUZO', true);
INSERT INTO sujeto.profesion (codigo, nombre, activo) VALUES ('112', 'CADENERO', true);
INSERT INTO sujeto.profesion (codigo, nombre, activo) VALUES ('113', 'CAFETERO', true);
INSERT INTO sujeto.profesion (codigo, nombre, activo) VALUES ('114', 'CAJERO', true);
INSERT INTO sujeto.profesion (codigo, nombre, activo) VALUES ('115', 'CALCULISTA', true);
INSERT INTO sujeto.profesion (codigo, nombre, activo) VALUES ('116', 'CALDERERO', true);
INSERT INTO sujeto.profesion (codigo, nombre, activo) VALUES ('117', 'CALIGRAFO', true);
INSERT INTO sujeto.profesion (codigo, nombre, activo) VALUES ('118', 'CAMARERO', true);
INSERT INTO sujeto.profesion (codigo, nombre, activo) VALUES ('119', 'CAMAROGRAFO', true);
INSERT INTO sujeto.profesion (codigo, nombre, activo) VALUES ('12', 'ADMINISTRADOR DE COMERCIO', true);
INSERT INTO sujeto.profesion (codigo, nombre, activo) VALUES ('120', 'CANASTERO', true);
INSERT INTO sujeto.profesion (codigo, nombre, activo) VALUES ('121', 'CANILLITA', true);
INSERT INTO sujeto.profesion (codigo, nombre, activo) VALUES ('122', 'CANTANTE', true);
INSERT INTO sujeto.profesion (codigo, nombre, activo) VALUES ('123', 'CANTERO', true);
INSERT INTO sujeto.profesion (codigo, nombre, activo) VALUES ('124', 'CANTINERO / BAR MAN', true);
INSERT INTO sujeto.profesion (codigo, nombre, activo) VALUES ('1244', 'TAPIZADOR', true);
INSERT INTO sujeto.profesion (codigo, nombre, activo) VALUES ('125', 'CAPATAZ', true);
INSERT INTO sujeto.profesion (codigo, nombre, activo) VALUES ('126', 'CARBONERO', true);
INSERT INTO sujeto.profesion (codigo, nombre, activo) VALUES ('127', 'CARGADOR', true);
INSERT INTO sujeto.profesion (codigo, nombre, activo) VALUES ('128', 'CARNICERO', true);
INSERT INTO sujeto.profesion (codigo, nombre, activo) VALUES ('129', 'CARPINTERO', true);
INSERT INTO sujeto.profesion (codigo, nombre, activo) VALUES ('13', 'ADMINISTRADOR DE CORREOS', true);
INSERT INTO sujeto.profesion (codigo, nombre, activo) VALUES ('130', 'CARRETONERO', true);
INSERT INTO sujeto.profesion (codigo, nombre, activo) VALUES ('131', 'CARROCERO', true);
INSERT INTO sujeto.profesion (codigo, nombre, activo) VALUES ('132', 'CARTERO', true);
INSERT INTO sujeto.profesion (codigo, nombre, activo) VALUES ('133', 'CARTOGRAFO', true);
INSERT INTO sujeto.profesion (codigo, nombre, activo) VALUES ('134', 'CARTONERO', true);
INSERT INTO sujeto.profesion (codigo, nombre, activo) VALUES ('135', 'CATADOR', true);
INSERT INTO sujeto.profesion (codigo, nombre, activo) VALUES ('136', 'CAUCHERO', true);
INSERT INTO sujeto.profesion (codigo, nombre, activo) VALUES ('137', 'CAZADOR', true);
INSERT INTO sujeto.profesion (codigo, nombre, activo) VALUES ('138', 'CEDACERO', true);
INSERT INTO sujeto.profesion (codigo, nombre, activo) VALUES ('139', 'CEGARRERO', true);
INSERT INTO sujeto.profesion (codigo, nombre, activo) VALUES ('14', 'ADMINISTRADOR DE EMPRESAS', true);
INSERT INTO sujeto.profesion (codigo, nombre, activo) VALUES ('140', 'CERAMISTA', true);
INSERT INTO sujeto.profesion (codigo, nombre, activo) VALUES ('141', 'CERRAJERO', true);
INSERT INTO sujeto.profesion (codigo, nombre, activo) VALUES ('142', 'CERVECERO', true);
INSERT INTO sujeto.profesion (codigo, nombre, activo) VALUES ('143', 'CHEFF', true);
INSERT INTO sujeto.profesion (codigo, nombre, activo) VALUES ('144', 'CHOCOLATERO', true);
INSERT INTO sujeto.profesion (codigo, nombre, activo) VALUES ('145', 'CHOFER PROFESIONAL', true);
INSERT INTO sujeto.profesion (codigo, nombre, activo) VALUES ('1451', 'APARADOR DE CALZADO', true);
INSERT INTO sujeto.profesion (codigo, nombre, activo) VALUES ('146', 'CINEASTA', true);
INSERT INTO sujeto.profesion (codigo, nombre, activo) VALUES ('147', 'CIRUJANO', true);
INSERT INTO sujeto.profesion (codigo, nombre, activo) VALUES ('148', 'CITOLOGO', true);
INSERT INTO sujeto.profesion (codigo, nombre, activo) VALUES ('149', 'CLASIFICADOR', true);
INSERT INTO sujeto.profesion (codigo, nombre, activo) VALUES ('15', 'ADMINISTRADOR DE FABRICAS', true);
INSERT INTO sujeto.profesion (codigo, nombre, activo) VALUES ('150', 'CLASIFICADOR DE BANANO', true);
INSERT INTO sujeto.profesion (codigo, nombre, activo) VALUES ('151', 'COBRADOR DE PASAJE', true);
INSERT INTO sujeto.profesion (codigo, nombre, activo) VALUES ('152', 'COCINERA', true);
INSERT INTO sujeto.profesion (codigo, nombre, activo) VALUES ('153', 'COLCHONERO', true);
INSERT INTO sujeto.profesion (codigo, nombre, activo) VALUES ('154', 'COLECTOR', true);
INSERT INTO sujeto.profesion (codigo, nombre, activo) VALUES ('1542', 'ABACERO', true);
INSERT INTO sujeto.profesion (codigo, nombre, activo) VALUES ('155', 'COLOCADOR DE VIDRIOS', true);
INSERT INTO sujeto.profesion (codigo, nombre, activo) VALUES ('156', 'COMERCIANTE', true);
INSERT INTO sujeto.profesion (codigo, nombre, activo) VALUES ('157', 'COMETOLOGO', true);
INSERT INTO sujeto.profesion (codigo, nombre, activo) VALUES ('158', 'COMISARIO', true);
INSERT INTO sujeto.profesion (codigo, nombre, activo) VALUES ('159', 'COMISIONISTA', true);
INSERT INTO sujeto.profesion (codigo, nombre, activo) VALUES ('16', 'ADMINISTRADOR DE HOTEL', true);
INSERT INTO sujeto.profesion (codigo, nombre, activo) VALUES ('160', 'CONDUCTOR', true);
INSERT INTO sujeto.profesion (codigo, nombre, activo) VALUES ('161', 'CONFITERO', true);
INSERT INTO sujeto.profesion (codigo, nombre, activo) VALUES ('162', 'CONSERJE', true);
INSERT INTO sujeto.profesion (codigo, nombre, activo) VALUES ('163', 'CONSERJERO SOCIAL', true);
INSERT INTO sujeto.profesion (codigo, nombre, activo) VALUES ('164', 'CONSTRUCTOR', true);
INSERT INTO sujeto.profesion (codigo, nombre, activo) VALUES ('165', 'CONTADOR', true);
INSERT INTO sujeto.profesion (codigo, nombre, activo) VALUES ('166', 'CONTADOR BACHILLER', true);
INSERT INTO sujeto.profesion (codigo, nombre, activo) VALUES ('167', 'CONTADOR BANCARIO', true);
INSERT INTO sujeto.profesion (codigo, nombre, activo) VALUES ('168', 'CONTRATISTA', true);
INSERT INTO sujeto.profesion (codigo, nombre, activo) VALUES ('169', 'CONTROLADOR', true);
INSERT INTO sujeto.profesion (codigo, nombre, activo) VALUES ('17', 'ADMINISTRADOR PUBLICO', true);
INSERT INTO sujeto.profesion (codigo, nombre, activo) VALUES ('170', 'CONTROLADOR TRAFICO AERERO', true);
INSERT INTO sujeto.profesion (codigo, nombre, activo) VALUES ('171', 'COOPERATIVISTA', true);
INSERT INTO sujeto.profesion (codigo, nombre, activo) VALUES ('172', 'CORREO/BIENES RAICES', true);
INSERT INTO sujeto.profesion (codigo, nombre, activo) VALUES ('173', 'CORRESPONSAL', true);
INSERT INTO sujeto.profesion (codigo, nombre, activo) VALUES ('174', 'CORTADOR', true);
INSERT INTO sujeto.profesion (codigo, nombre, activo) VALUES ('175', 'COSEDOR', true);
INSERT INTO sujeto.profesion (codigo, nombre, activo) VALUES ('176', 'COSTURERA', true);
INSERT INTO sujeto.profesion (codigo, nombre, activo) VALUES ('177', 'CRIMINOLOGO', true);
INSERT INTO sujeto.profesion (codigo, nombre, activo) VALUES ('178', 'CRITICO', true);
INSERT INTO sujeto.profesion (codigo, nombre, activo) VALUES ('179', 'CRONISTA', true);
INSERT INTO sujeto.profesion (codigo, nombre, activo) VALUES ('18', 'ADOBERO', true);
INSERT INTO sujeto.profesion (codigo, nombre, activo) VALUES ('180', 'CURTIDOR', true);
INSERT INTO sujeto.profesion (codigo, nombre, activo) VALUES ('181', 'DACTILOGRAFO', true);
INSERT INTO sujeto.profesion (codigo, nombre, activo) VALUES ('182', 'DAMA DE COMPANIA', true);
INSERT INTO sujeto.profesion (codigo, nombre, activo) VALUES ('183', 'DEALER DE CASINO', true);
INSERT INTO sujeto.profesion (codigo, nombre, activo) VALUES ('184', 'DECORADOR', true);
INSERT INTO sujeto.profesion (codigo, nombre, activo) VALUES ('185', 'DEM. BELLEZA', true);
INSERT INTO sujeto.profesion (codigo, nombre, activo) VALUES ('186', 'DEPENDIENTE', true);
INSERT INTO sujeto.profesion (codigo, nombre, activo) VALUES ('187', 'DEPORTISTA', true);
INSERT INTO sujeto.profesion (codigo, nombre, activo) VALUES ('188', 'DESCARNADOR', true);
INSERT INTO sujeto.profesion (codigo, nombre, activo) VALUES ('189', 'DESMOTADOR', true);
INSERT INTO sujeto.profesion (codigo, nombre, activo) VALUES ('19', 'AFILADOR', true);
INSERT INTO sujeto.profesion (codigo, nombre, activo) VALUES ('190', 'DESPACHADOR', true);
INSERT INTO sujeto.profesion (codigo, nombre, activo) VALUES ('191', 'DESTILADOR', true);
INSERT INTO sujeto.profesion (codigo, nombre, activo) VALUES ('192', 'DETECTIVE', true);
INSERT INTO sujeto.profesion (codigo, nombre, activo) VALUES ('193', 'DIBUJANTE', true);
INSERT INTO sujeto.profesion (codigo, nombre, activo) VALUES ('194', 'DIETISTA', true);
INSERT INTO sujeto.profesion (codigo, nombre, activo) VALUES ('195', 'DIGITADOR', true);
INSERT INTO sujeto.profesion (codigo, nombre, activo) VALUES ('196', 'DIPLOMATICO', true);
INSERT INTO sujeto.profesion (codigo, nombre, activo) VALUES ('197', 'DIRECTOR', true);
INSERT INTO sujeto.profesion (codigo, nombre, activo) VALUES ('198', 'DIRECTOR TECNICO', true);
INSERT INTO sujeto.profesion (codigo, nombre, activo) VALUES ('199', 'DISEÑADOR', true);
INSERT INTO sujeto.profesion (codigo, nombre, activo) VALUES ('2', 'ABOGADO', true);
INSERT INTO sujeto.profesion (codigo, nombre, activo) VALUES ('20', 'AGENTE COMP. NAVIERA', true);
INSERT INTO sujeto.profesion (codigo, nombre, activo) VALUES ('200', 'DISTRIBUIDOR', true);
INSERT INTO sujeto.profesion (codigo, nombre, activo) VALUES ('201', 'DOMADOR', true);
INSERT INTO sujeto.profesion (codigo, nombre, activo) VALUES ('202', 'DORADOR', true);
INSERT INTO sujeto.profesion (codigo, nombre, activo) VALUES ('203', 'DR. ADMINISTRACION', true);
INSERT INTO sujeto.profesion (codigo, nombre, activo) VALUES ('204', 'DR. BIOQUIMICO Y FARMACEUTICO', true);
INSERT INTO sujeto.profesion (codigo, nombre, activo) VALUES ('205', 'DR. CC. NATURALES', true);
INSERT INTO sujeto.profesion (codigo, nombre, activo) VALUES ('206', 'DR. CC. POLITICAS', true);
INSERT INTO sujeto.profesion (codigo, nombre, activo) VALUES ('207', 'DR. CONTABILIDAD', true);
INSERT INTO sujeto.profesion (codigo, nombre, activo) VALUES ('208', 'DR. ECONOMIA', true);
INSERT INTO sujeto.profesion (codigo, nombre, activo) VALUES ('209', 'DR. EN AGRONOMIA', true);
INSERT INTO sujeto.profesion (codigo, nombre, activo) VALUES ('21', 'AGENTE DE ADUANA', true);
INSERT INTO sujeto.profesion (codigo, nombre, activo) VALUES ('210', 'DR. EN BIOLOGIA', true);
INSERT INTO sujeto.profesion (codigo, nombre, activo) VALUES ('211', 'DR. EN DERECHO', true);
INSERT INTO sujeto.profesion (codigo, nombre, activo) VALUES ('212', 'DR. EN DERECHO INTERNACIONAL', true);
INSERT INTO sujeto.profesion (codigo, nombre, activo) VALUES ('213', 'DR. EN EDUCACION', true);
INSERT INTO sujeto.profesion (codigo, nombre, activo) VALUES ('214', 'DR. EN JURISPRUDENCIA', true);
INSERT INTO sujeto.profesion (codigo, nombre, activo) VALUES ('215', 'DR. EN LINGUISTICA', true);
INSERT INTO sujeto.profesion (codigo, nombre, activo) VALUES ('216', 'DR. EN MATEMATICAS', true);
INSERT INTO sujeto.profesion (codigo, nombre, activo) VALUES ('217', 'DR. EN PSICOLOGIA', true);
INSERT INTO sujeto.profesion (codigo, nombre, activo) VALUES ('218', 'DR. EN QUIMICA', true);
INSERT INTO sujeto.profesion (codigo, nombre, activo) VALUES ('219', 'DR. FILOSOFIA Y LETRAS', true);
INSERT INTO sujeto.profesion (codigo, nombre, activo) VALUES ('22', 'AGENTE DE BIENES RAICES', true);
INSERT INTO sujeto.profesion (codigo, nombre, activo) VALUES ('220', 'DR. MEDICINA', true);
INSERT INTO sujeto.profesion (codigo, nombre, activo) VALUES ('221', 'DR. MEDICINA VETERINARIA', true);
INSERT INTO sujeto.profesion (codigo, nombre, activo) VALUES ('222', 'DR. NUTRICION HUMANA', true);
INSERT INTO sujeto.profesion (codigo, nombre, activo) VALUES ('223', 'DR. PSICOLOGIA CLINICA', true);
INSERT INTO sujeto.profesion (codigo, nombre, activo) VALUES ('224', 'DR. PSICOLOGIA INDUSTRIAL', true);
INSERT INTO sujeto.profesion (codigo, nombre, activo) VALUES ('225', 'DR. PSICOLOGIA JURIDICA', true);
INSERT INTO sujeto.profesion (codigo, nombre, activo) VALUES ('226', 'DR. QUIMICA FARMACIA', true);
INSERT INTO sujeto.profesion (codigo, nombre, activo) VALUES ('227', 'DR. QUIMICO INDUSTRIAL', true);
INSERT INTO sujeto.profesion (codigo, nombre, activo) VALUES ('228', 'DULCERO', true);
INSERT INTO sujeto.profesion (codigo, nombre, activo) VALUES ('229', 'EBANISTA', true);
INSERT INTO sujeto.profesion (codigo, nombre, activo) VALUES ('23', 'AGENTE DE PUBLICIDAD', true);
INSERT INTO sujeto.profesion (codigo, nombre, activo) VALUES ('230', 'ECONOMISTA', true);
INSERT INTO sujeto.profesion (codigo, nombre, activo) VALUES ('231', 'ECONOMO', true);
INSERT INTO sujeto.profesion (codigo, nombre, activo) VALUES ('232', 'EDUCADOR PARVULARIO', true);
INSERT INTO sujeto.profesion (codigo, nombre, activo) VALUES ('233', 'EGRESADO/A', true);
INSERT INTO sujeto.profesion (codigo, nombre, activo) VALUES ('234', 'EJECUTIVO', true);
INSERT INTO sujeto.profesion (codigo, nombre, activo) VALUES ('235', 'ELECTRICISTA', true);
INSERT INTO sujeto.profesion (codigo, nombre, activo) VALUES ('236', 'ELECTROTIPISTA', true);
INSERT INTO sujeto.profesion (codigo, nombre, activo) VALUES ('237', 'EMBALZAMADOR', true);
INSERT INTO sujeto.profesion (codigo, nombre, activo) VALUES ('238', 'EMBAZADOR', true);
INSERT INTO sujeto.profesion (codigo, nombre, activo) VALUES ('239', 'EMBELLECEDOR', true);
INSERT INTO sujeto.profesion (codigo, nombre, activo) VALUES ('24', 'AGENTE DE SEGUROS', true);
INSERT INTO sujeto.profesion (codigo, nombre, activo) VALUES ('240', 'EMBOTELLADOR', true);
INSERT INTO sujeto.profesion (codigo, nombre, activo) VALUES ('241', 'EMPACADOR', true);
INSERT INTO sujeto.profesion (codigo, nombre, activo) VALUES ('242', 'EMPALMADOR', true);
INSERT INTO sujeto.profesion (codigo, nombre, activo) VALUES ('243', 'EMPAQUETADOR', true);
INSERT INTO sujeto.profesion (codigo, nombre, activo) VALUES ('244', 'EMPLEADA DOMESTICA', true);
INSERT INTO sujeto.profesion (codigo, nombre, activo) VALUES ('245', 'EMPLEADO', true);
INSERT INTO sujeto.profesion (codigo, nombre, activo) VALUES ('246', 'EMPLEADO BANCARIO', true);
INSERT INTO sujeto.profesion (codigo, nombre, activo) VALUES ('247', 'EMPLEADO PARTICULAR', true);
INSERT INTO sujeto.profesion (codigo, nombre, activo) VALUES ('248', 'EMPLEADO PRIVADO', true);
INSERT INTO sujeto.profesion (codigo, nombre, activo) VALUES ('249', 'EMPLEADO PUBLICO', true);
INSERT INTO sujeto.profesion (codigo, nombre, activo) VALUES ('25', 'AGENTE DE TURISMO', true);
INSERT INTO sujeto.profesion (codigo, nombre, activo) VALUES ('250', 'EMPLEADOR', true);
INSERT INTO sujeto.profesion (codigo, nombre, activo) VALUES ('251', 'EMPRESARIO', true);
INSERT INTO sujeto.profesion (codigo, nombre, activo) VALUES ('252', 'ENCERADOR', true);
INSERT INTO sujeto.profesion (codigo, nombre, activo) VALUES ('253', 'ENCHAPADOR', true);
INSERT INTO sujeto.profesion (codigo, nombre, activo) VALUES ('254', 'ENCUADERNADOR', true);
INSERT INTO sujeto.profesion (codigo, nombre, activo) VALUES ('255', 'ENDEREZADOR', true);
INSERT INTO sujeto.profesion (codigo, nombre, activo) VALUES ('256', 'ENFERMERO/A', true);
INSERT INTO sujeto.profesion (codigo, nombre, activo) VALUES ('257', 'ENLADRILLADOR', true);
INSERT INTO sujeto.profesion (codigo, nombre, activo) VALUES ('258', 'ENLATADOR', true);
INSERT INTO sujeto.profesion (codigo, nombre, activo) VALUES ('259', 'ENLOSADOR', true);
INSERT INTO sujeto.profesion (codigo, nombre, activo) VALUES ('26', 'AGENTE JUDICIAL', true);
INSERT INTO sujeto.profesion (codigo, nombre, activo) VALUES ('260', 'ENTEJADOR', true);
INSERT INTO sujeto.profesion (codigo, nombre, activo) VALUES ('261', 'ENTRENADOR', true);
INSERT INTO sujeto.profesion (codigo, nombre, activo) VALUES ('262', 'EQUITADOR', true);
INSERT INTO sujeto.profesion (codigo, nombre, activo) VALUES ('263', 'ESCOBERO', true);
INSERT INTO sujeto.profesion (codigo, nombre, activo) VALUES ('264', 'ESCRIBANO', true);
INSERT INTO sujeto.profesion (codigo, nombre, activo) VALUES ('265', 'ESCRITOR', true);
INSERT INTO sujeto.profesion (codigo, nombre, activo) VALUES ('266', 'ESCULTOR', true);
INSERT INTO sujeto.profesion (codigo, nombre, activo) VALUES ('267', 'ESTADISTICO', true);
INSERT INTO sujeto.profesion (codigo, nombre, activo) VALUES ('268', 'ESTEREOTIPISTA', true);
INSERT INTO sujeto.profesion (codigo, nombre, activo) VALUES ('269', 'ESTIBADOR', true);
INSERT INTO sujeto.profesion (codigo, nombre, activo) VALUES ('27', 'AGENTE R. COMERCIAL', true);
INSERT INTO sujeto.profesion (codigo, nombre, activo) VALUES ('270', 'ESTILISTA', true);
INSERT INTO sujeto.profesion (codigo, nombre, activo) VALUES ('271', 'ESTIQUETADOR', true);
INSERT INTO sujeto.profesion (codigo, nombre, activo) VALUES ('272', 'ESTUDIANTE', true);
INSERT INTO sujeto.profesion (codigo, nombre, activo) VALUES ('273', 'ESTUQUERO', true);
INSERT INTO sujeto.profesion (codigo, nombre, activo) VALUES ('274', 'EXPERTO', true);
INSERT INTO sujeto.profesion (codigo, nombre, activo) VALUES ('275', 'EXPLORADOR', true);
INSERT INTO sujeto.profesion (codigo, nombre, activo) VALUES ('276', 'FARACEUTICO', true);
INSERT INTO sujeto.profesion (codigo, nombre, activo) VALUES ('277', 'FERROVIARIO', true);
INSERT INTO sujeto.profesion (codigo, nombre, activo) VALUES ('278', 'FIERRERO', true);
INSERT INTO sujeto.profesion (codigo, nombre, activo) VALUES ('279', 'FILOLOGO', true);
INSERT INTO sujeto.profesion (codigo, nombre, activo) VALUES ('28', 'AGENTE VIAJERO', true);
INSERT INTO sujeto.profesion (codigo, nombre, activo) VALUES ('280', 'FISCAL', true);
INSERT INTO sujeto.profesion (codigo, nombre, activo) VALUES ('281', 'FISCALIZADOR', true);
INSERT INTO sujeto.profesion (codigo, nombre, activo) VALUES ('282', 'FISICO', true);
INSERT INTO sujeto.profesion (codigo, nombre, activo) VALUES ('283', 'FISIOTERAPISTA', true);
INSERT INTO sujeto.profesion (codigo, nombre, activo) VALUES ('284', 'FLORICULTOR', true);
INSERT INTO sujeto.profesion (codigo, nombre, activo) VALUES ('285', 'FLORISTERI', true);
INSERT INTO sujeto.profesion (codigo, nombre, activo) VALUES ('286', 'FOGONERO', true);
INSERT INTO sujeto.profesion (codigo, nombre, activo) VALUES ('287', 'FONDERO', true);
INSERT INTO sujeto.profesion (codigo, nombre, activo) VALUES ('288', 'FONTANERO', true);
INSERT INTO sujeto.profesion (codigo, nombre, activo) VALUES ('289', 'FORESTAL', true);
INSERT INTO sujeto.profesion (codigo, nombre, activo) VALUES ('29', 'AGRICULTOR', true);
INSERT INTO sujeto.profesion (codigo, nombre, activo) VALUES ('290', 'FOTOGRABADOR', true);
INSERT INTO sujeto.profesion (codigo, nombre, activo) VALUES ('291', 'FOTOGRAFO', true);
INSERT INTO sujeto.profesion (codigo, nombre, activo) VALUES ('292', 'FOTOGRAMETRISTA', true);
INSERT INTO sujeto.profesion (codigo, nombre, activo) VALUES ('293', 'FOTOMECANICO', true);
INSERT INTO sujeto.profesion (codigo, nombre, activo) VALUES ('294', 'FUMIGADOR', true);
INSERT INTO sujeto.profesion (codigo, nombre, activo) VALUES ('295', 'FUNDIDOR EN GENERAL', true);
INSERT INTO sujeto.profesion (codigo, nombre, activo) VALUES ('296', 'FUTBOLISTA', true);
INSERT INTO sujeto.profesion (codigo, nombre, activo) VALUES ('297', 'GALVANIZADOR', true);
INSERT INTO sujeto.profesion (codigo, nombre, activo) VALUES ('298', 'GANADERO', true);
INSERT INTO sujeto.profesion (codigo, nombre, activo) VALUES ('299', 'GASFITERO', true);
INSERT INTO sujeto.profesion (codigo, nombre, activo) VALUES ('3', 'ACEITADOR', true);
INSERT INTO sujeto.profesion (codigo, nombre, activo) VALUES ('30', 'AGRIMESOR', true);
INSERT INTO sujeto.profesion (codigo, nombre, activo) VALUES ('300', 'GEOLOGO', true);
INSERT INTO sujeto.profesion (codigo, nombre, activo) VALUES ('3001', 'ING EN ECOTURISMO', true);
INSERT INTO sujeto.profesion (codigo, nombre, activo) VALUES ('301', 'GERENTE', true);
INSERT INTO sujeto.profesion (codigo, nombre, activo) VALUES ('302', 'GINECOLOGO', true);
INSERT INTO sujeto.profesion (codigo, nombre, activo) VALUES ('303', 'GRABADOR EN GENERAL', true);
INSERT INTO sujeto.profesion (codigo, nombre, activo) VALUES ('304', 'GRAFICO PRENSISTA', true);
INSERT INTO sujeto.profesion (codigo, nombre, activo) VALUES ('305', 'GUARDA FORESTAL', true);
INSERT INTO sujeto.profesion (codigo, nombre, activo) VALUES ('306', 'GUARDA ROPAS', true);
INSERT INTO sujeto.profesion (codigo, nombre, activo) VALUES ('307', 'GUARDIA', true);
INSERT INTO sujeto.profesion (codigo, nombre, activo) VALUES ('308', 'GUARDIAN', true);
INSERT INTO sujeto.profesion (codigo, nombre, activo) VALUES ('309', 'GUIA TURISTICO', true);
INSERT INTO sujeto.profesion (codigo, nombre, activo) VALUES ('31', 'AGRONOMO', true);
INSERT INTO sujeto.profesion (codigo, nombre, activo) VALUES ('310', 'HACHERO', true);
INSERT INTO sujeto.profesion (codigo, nombre, activo) VALUES ('311', 'HELADERO', true);
INSERT INTO sujeto.profesion (codigo, nombre, activo) VALUES ('312', 'HERBOLOGO', true);
INSERT INTO sujeto.profesion (codigo, nombre, activo) VALUES ('313', 'HERRERO', true);
INSERT INTO sujeto.profesion (codigo, nombre, activo) VALUES ('314', 'HILANDERO', true);
INSERT INTO sujeto.profesion (codigo, nombre, activo) VALUES ('315', 'HIPNOTIZADOR', true);
INSERT INTO sujeto.profesion (codigo, nombre, activo) VALUES ('316', 'HISTORIADOR', true);
INSERT INTO sujeto.profesion (codigo, nombre, activo) VALUES ('317', 'HOJALATERO', true);
INSERT INTO sujeto.profesion (codigo, nombre, activo) VALUES ('318', 'HORNERO', true);
INSERT INTO sujeto.profesion (codigo, nombre, activo) VALUES ('319', 'HORTELANO', true);
INSERT INTO sujeto.profesion (codigo, nombre, activo) VALUES ('32', 'AGUATERO', true);
INSERT INTO sujeto.profesion (codigo, nombre, activo) VALUES ('320', 'HORTICULTOR', true);
INSERT INTO sujeto.profesion (codigo, nombre, activo) VALUES ('321', 'HOSTELERO', true);
INSERT INTO sujeto.profesion (codigo, nombre, activo) VALUES ('322', 'HOTELERO', true);
INSERT INTO sujeto.profesion (codigo, nombre, activo) VALUES ('323', 'IMPORTADOR', true);
INSERT INTO sujeto.profesion (codigo, nombre, activo) VALUES ('324', 'IMPRESOR', true);
INSERT INTO sujeto.profesion (codigo, nombre, activo) VALUES ('325', 'INDUSTRIAL', true);
INSERT INTO sujeto.profesion (codigo, nombre, activo) VALUES ('326', 'ING. AERONAUTICO', true);
INSERT INTO sujeto.profesion (codigo, nombre, activo) VALUES ('327', 'ING. AGRICOLA', true);
INSERT INTO sujeto.profesion (codigo, nombre, activo) VALUES ('328', 'ING. AGRONOMO', true);
INSERT INTO sujeto.profesion (codigo, nombre, activo) VALUES ('329', 'ING. BURSATIL', true);
INSERT INTO sujeto.profesion (codigo, nombre, activo) VALUES ('33', 'AJUST. DE SINIESTROS', true);
INSERT INTO sujeto.profesion (codigo, nombre, activo) VALUES ('330', 'ING. CIVIL', true);
INSERT INTO sujeto.profesion (codigo, nombre, activo) VALUES ('331', 'ING. COMERCIAL', true);
INSERT INTO sujeto.profesion (codigo, nombre, activo) VALUES ('332', 'ING. DE AUDIO', true);
INSERT INTO sujeto.profesion (codigo, nombre, activo) VALUES ('333', 'ING. DE EMPRESAS', true);
INSERT INTO sujeto.profesion (codigo, nombre, activo) VALUES ('334', 'ING. DE MINAS', true);
INSERT INTO sujeto.profesion (codigo, nombre, activo) VALUES ('335', 'ING. DE PETROLEOS', true);
INSERT INTO sujeto.profesion (codigo, nombre, activo) VALUES ('336', 'ING. DE SISTEMAS', true);
INSERT INTO sujeto.profesion (codigo, nombre, activo) VALUES ('337', 'ING. DE VUELO', true);
INSERT INTO sujeto.profesion (codigo, nombre, activo) VALUES ('338', 'ING. ELECTRICO', true);
INSERT INTO sujeto.profesion (codigo, nombre, activo) VALUES ('339', 'ING. ELECTRICO', true);
INSERT INTO sujeto.profesion (codigo, nombre, activo) VALUES ('34', 'ALBAÑIL', true);
INSERT INTO sujeto.profesion (codigo, nombre, activo) VALUES ('340', 'ING. EN ALIMENTOS', true);
INSERT INTO sujeto.profesion (codigo, nombre, activo) VALUES ('341', 'ING. EN INFORMATICA', true);
INSERT INTO sujeto.profesion (codigo, nombre, activo) VALUES ('342', 'ING. FORESTAL', true);
INSERT INTO sujeto.profesion (codigo, nombre, activo) VALUES ('343', 'ING. GEOGRAFO', true);
INSERT INTO sujeto.profesion (codigo, nombre, activo) VALUES ('344', 'ING. GEOLOGO', true);
INSERT INTO sujeto.profesion (codigo, nombre, activo) VALUES ('345', 'ING. HIDROGEOLOGIA MINERO', true);
INSERT INTO sujeto.profesion (codigo, nombre, activo) VALUES ('346', 'ING. HIDROLOGO', true);
INSERT INTO sujeto.profesion (codigo, nombre, activo) VALUES ('347', 'ING. IND. AGROPECUARIA', true);
INSERT INTO sujeto.profesion (codigo, nombre, activo) VALUES ('348', 'ING. INSDUSTRIAL', true);
INSERT INTO sujeto.profesion (codigo, nombre, activo) VALUES ('349', 'ING. MECANICO', true);
INSERT INTO sujeto.profesion (codigo, nombre, activo) VALUES ('35', 'ALFABETIZADOR', true);
INSERT INTO sujeto.profesion (codigo, nombre, activo) VALUES ('350', 'ING. METEOROLOGO', true);
INSERT INTO sujeto.profesion (codigo, nombre, activo) VALUES ('351', 'ING. QUIMICO', true);
INSERT INTO sujeto.profesion (codigo, nombre, activo) VALUES ('352', 'ING. ZOOTECNISTA', true);
INSERT INTO sujeto.profesion (codigo, nombre, activo) VALUES ('353', 'INGENIERO', true);
INSERT INTO sujeto.profesion (codigo, nombre, activo) VALUES ('354', 'INGENIERO NAVAL', true);
INSERT INTO sujeto.profesion (codigo, nombre, activo) VALUES ('355', 'INGENIERO TEXTIL', true);
INSERT INTO sujeto.profesion (codigo, nombre, activo) VALUES ('356', 'INSPECTOR', true);
INSERT INTO sujeto.profesion (codigo, nombre, activo) VALUES ('357', 'INSTRUCTOR', true);
INSERT INTO sujeto.profesion (codigo, nombre, activo) VALUES ('358', 'INSTRUM. QUIRURGICO', true);
INSERT INTO sujeto.profesion (codigo, nombre, activo) VALUES ('359', 'INTERMEDIARIO', true);
INSERT INTO sujeto.profesion (codigo, nombre, activo) VALUES ('36', 'ALFARERO', true);
INSERT INTO sujeto.profesion (codigo, nombre, activo) VALUES ('360', 'INTERPRETE', true);
INSERT INTO sujeto.profesion (codigo, nombre, activo) VALUES ('361', 'INTROD. GANADO', true);
INSERT INTO sujeto.profesion (codigo, nombre, activo) VALUES ('362', 'INTRUM. INDUSTRIAL', true);
INSERT INTO sujeto.profesion (codigo, nombre, activo) VALUES ('363', 'INVERSIONISTA', true);
INSERT INTO sujeto.profesion (codigo, nombre, activo) VALUES ('364', 'INVESTIGADOR PRIVADO', true);
INSERT INTO sujeto.profesion (codigo, nombre, activo) VALUES ('365', 'JABONERO', true);
INSERT INTO sujeto.profesion (codigo, nombre, activo) VALUES ('366', 'JARDINERO', true);
INSERT INTO sujeto.profesion (codigo, nombre, activo) VALUES ('367', 'JEFE EN GENERAL', true);
INSERT INTO sujeto.profesion (codigo, nombre, activo) VALUES ('368', 'JIFERO', true);
INSERT INTO sujeto.profesion (codigo, nombre, activo) VALUES ('369', 'JOCKEY', true);
INSERT INTO sujeto.profesion (codigo, nombre, activo) VALUES ('37', 'ALFOMBRERO', true);
INSERT INTO sujeto.profesion (codigo, nombre, activo) VALUES ('370', 'JUBILADO', true);
INSERT INTO sujeto.profesion (codigo, nombre, activo) VALUES ('371', 'JUEZ', true);
INSERT INTO sujeto.profesion (codigo, nombre, activo) VALUES ('372', 'LABORATORISTA', true);
INSERT INTO sujeto.profesion (codigo, nombre, activo) VALUES ('373', 'LADRILLERO', true);
INSERT INTO sujeto.profesion (codigo, nombre, activo) VALUES ('374', 'LAMINADOR', true);
INSERT INTO sujeto.profesion (codigo, nombre, activo) VALUES ('375', 'LANCHERO', true);
INSERT INTO sujeto.profesion (codigo, nombre, activo) VALUES ('376', 'LAQUEADOR', true);
INSERT INTO sujeto.profesion (codigo, nombre, activo) VALUES ('377', 'LATONERO', true);
INSERT INTO sujeto.profesion (codigo, nombre, activo) VALUES ('378', 'LAVANDERO/A', true);
INSERT INTO sujeto.profesion (codigo, nombre, activo) VALUES ('379', 'LEÑADOR', true);
INSERT INTO sujeto.profesion (codigo, nombre, activo) VALUES ('38', 'ALPARGATERO', true);
INSERT INTO sujeto.profesion (codigo, nombre, activo) VALUES ('380', 'LIBRERO', true);
INSERT INTO sujeto.profesion (codigo, nombre, activo) VALUES ('381', 'LIC. /ENFERMERIA', true);
INSERT INTO sujeto.profesion (codigo, nombre, activo) VALUES ('382', 'LIC. ADMINIS. EMPRESAS', true);
INSERT INTO sujeto.profesion (codigo, nombre, activo) VALUES ('383', 'LIC. ADMINIS. PUBLICA', true);
INSERT INTO sujeto.profesion (codigo, nombre, activo) VALUES ('384', 'LIC. CC. COM. SOCIAL', true);
INSERT INTO sujeto.profesion (codigo, nombre, activo) VALUES ('385', 'LIC. CC. EDUCACION', true);
INSERT INTO sujeto.profesion (codigo, nombre, activo) VALUES ('386', 'LIC. CC. INFORMATICA', true);
INSERT INTO sujeto.profesion (codigo, nombre, activo) VALUES ('387', 'LIC. CC. PUB. Y SOC.', true);
INSERT INTO sujeto.profesion (codigo, nombre, activo) VALUES ('388', 'LIC. COMERCIO EXTRANJERO', true);
INSERT INTO sujeto.profesion (codigo, nombre, activo) VALUES ('389', 'LIC. CONTABILIDAD Y AUDITORIA', true);
INSERT INTO sujeto.profesion (codigo, nombre, activo) VALUES ('39', 'ALPINISTA', true);
INSERT INTO sujeto.profesion (codigo, nombre, activo) VALUES ('390', 'LIC. COSTOS INDUSTRIALES', true);
INSERT INTO sujeto.profesion (codigo, nombre, activo) VALUES ('391', 'LIC. EN BANCA', true);
INSERT INTO sujeto.profesion (codigo, nombre, activo) VALUES ('392', 'LIC. EN ESTADISTICA', true);
INSERT INTO sujeto.profesion (codigo, nombre, activo) VALUES ('393', 'LIC. EN LINGUISTICA', true);
INSERT INTO sujeto.profesion (codigo, nombre, activo) VALUES ('394', 'LIC. EN NUTRICION Y DIETETICA', true);
INSERT INTO sujeto.profesion (codigo, nombre, activo) VALUES ('395', 'LIC. EN SOCIOLOGIA', true);
INSERT INTO sujeto.profesion (codigo, nombre, activo) VALUES ('396', 'LIC. PSICOLOGIA', true);
INSERT INTO sujeto.profesion (codigo, nombre, activo) VALUES ('397', 'LIC. RECREACION INFANTIL', true);
INSERT INTO sujeto.profesion (codigo, nombre, activo) VALUES ('398', 'LIC. RELACIONES PUBLICAS', true);
INSERT INTO sujeto.profesion (codigo, nombre, activo) VALUES ('399', 'LIC. SERVICIO SOCIAL', true);
INSERT INTO sujeto.profesion (codigo, nombre, activo) VALUES ('4', 'ACOMODADOR DE CINE', true);
INSERT INTO sujeto.profesion (codigo, nombre, activo) VALUES ('40', 'AMA DE LLAVES', true);
INSERT INTO sujeto.profesion (codigo, nombre, activo) VALUES ('400', 'LICENCIADO/A', true);
INSERT INTO sujeto.profesion (codigo, nombre, activo) VALUES ('401', 'LIMPIABOTAS', true);
INSERT INTO sujeto.profesion (codigo, nombre, activo) VALUES ('402', 'LIMPIADOR', true);
INSERT INTO sujeto.profesion (codigo, nombre, activo) VALUES ('403', 'LINGUISTA', true);
INSERT INTO sujeto.profesion (codigo, nombre, activo) VALUES ('404', 'LINOTIPISTA', true);
INSERT INTO sujeto.profesion (codigo, nombre, activo) VALUES ('405', 'LITERATO', true);
INSERT INTO sujeto.profesion (codigo, nombre, activo) VALUES ('406', 'LITOGRAFO', true);
INSERT INTO sujeto.profesion (codigo, nombre, activo) VALUES ('407', 'LOCUTOR', true);
INSERT INTO sujeto.profesion (codigo, nombre, activo) VALUES ('408', 'LOTERO', true);
INSERT INTO sujeto.profesion (codigo, nombre, activo) VALUES ('409', 'MACANERA', true);
INSERT INTO sujeto.profesion (codigo, nombre, activo) VALUES ('41', 'AMANUENSE', true);
INSERT INTO sujeto.profesion (codigo, nombre, activo) VALUES ('410', 'MADERERO/A', true);
INSERT INTO sujeto.profesion (codigo, nombre, activo) VALUES ('411', 'MAESTRA CONFECCION INDUSTRIAL', true);
INSERT INTO sujeto.profesion (codigo, nombre, activo) VALUES ('412', 'MAESTRA CORTE CONFECCION', true);
INSERT INTO sujeto.profesion (codigo, nombre, activo) VALUES ('413', 'MAESTRO/A BELLEZA', true);
INSERT INTO sujeto.profesion (codigo, nombre, activo) VALUES ('414', 'MAESTRO/A ELECT/INDUSTR.', true);
INSERT INTO sujeto.profesion (codigo, nombre, activo) VALUES ('415', 'MAESTRO/A EN ARTES', true);
INSERT INTO sujeto.profesion (codigo, nombre, activo) VALUES ('416', 'MAESTRO/A IMPRESOR', true);
INSERT INTO sujeto.profesion (codigo, nombre, activo) VALUES ('417', 'MAESTRO/A PLANIFICADOR', true);
INSERT INTO sujeto.profesion (codigo, nombre, activo) VALUES ('418', 'MAESTRO/A SASTRERIA', true);
INSERT INTO sujeto.profesion (codigo, nombre, activo) VALUES ('419', 'MAGISTRADO', true);
INSERT INTO sujeto.profesion (codigo, nombre, activo) VALUES ('42', 'ANALISTA', true);
INSERT INTO sujeto.profesion (codigo, nombre, activo) VALUES ('420', 'MANICURISTA', true);
INSERT INTO sujeto.profesion (codigo, nombre, activo) VALUES ('421', 'MANTEQUERO', true);
INSERT INTO sujeto.profesion (codigo, nombre, activo) VALUES ('422', 'MANTEQUILLADOR', true);
INSERT INTO sujeto.profesion (codigo, nombre, activo) VALUES ('423', 'MANUFACTURERO', true);
INSERT INTO sujeto.profesion (codigo, nombre, activo) VALUES ('424', 'MAQUINISTA', true);
INSERT INTO sujeto.profesion (codigo, nombre, activo) VALUES ('425', 'MARINERO', true);
INSERT INTO sujeto.profesion (codigo, nombre, activo) VALUES ('426', 'MARINO DE GUERRA', true);
INSERT INTO sujeto.profesion (codigo, nombre, activo) VALUES ('427', 'MARINO MERCANTE', true);
INSERT INTO sujeto.profesion (codigo, nombre, activo) VALUES ('428', 'MARMOLERO', true);
INSERT INTO sujeto.profesion (codigo, nombre, activo) VALUES ('429', 'MASAJISTA', true);
INSERT INTO sujeto.profesion (codigo, nombre, activo) VALUES ('43', 'ANALISTA DE SISTEMAS', true);
INSERT INTO sujeto.profesion (codigo, nombre, activo) VALUES ('430', 'MASTER C. FILOSOFICAS', true);
INSERT INTO sujeto.profesion (codigo, nombre, activo) VALUES ('431', 'MASTER CC. EDUCACION', true);
INSERT INTO sujeto.profesion (codigo, nombre, activo) VALUES ('432', 'MASTER CC. HISTORICAS', true);
INSERT INTO sujeto.profesion (codigo, nombre, activo) VALUES ('433', 'MASTER ELECTRONICA', true);
INSERT INTO sujeto.profesion (codigo, nombre, activo) VALUES ('434', 'MASTER EN ECONOMIA', true);
INSERT INTO sujeto.profesion (codigo, nombre, activo) VALUES ('435', 'MASTER EN FISICA', true);
INSERT INTO sujeto.profesion (codigo, nombre, activo) VALUES ('436', 'MATARIFE', true);
INSERT INTO sujeto.profesion (codigo, nombre, activo) VALUES ('437', 'MATEMATICO', true);
INSERT INTO sujeto.profesion (codigo, nombre, activo) VALUES ('438', 'MATRICERO', true);
INSERT INTO sujeto.profesion (codigo, nombre, activo) VALUES ('439', 'MAYORDOMO', true);
INSERT INTO sujeto.profesion (codigo, nombre, activo) VALUES ('44', 'ANTROPOLOGO', true);
INSERT INTO sujeto.profesion (codigo, nombre, activo) VALUES ('440', 'MECANICO', true);
INSERT INTO sujeto.profesion (codigo, nombre, activo) VALUES ('441', 'MECANICO AUTOMOTRIZ', true);
INSERT INTO sujeto.profesion (codigo, nombre, activo) VALUES ('442', 'MECANICO DE PRECISION', true);
INSERT INTO sujeto.profesion (codigo, nombre, activo) VALUES ('443', 'MECANICO DE VUELO', true);
INSERT INTO sujeto.profesion (codigo, nombre, activo) VALUES ('444', 'MECANICO DENTAL', true);
INSERT INTO sujeto.profesion (codigo, nombre, activo) VALUES ('445', 'MECANICO INDUSTRIAL', true);
INSERT INTO sujeto.profesion (codigo, nombre, activo) VALUES ('446', 'MECANICO MANTENIMIENTO AVIONES', true);
INSERT INTO sujeto.profesion (codigo, nombre, activo) VALUES ('447', 'MECANICO ORTOPEDICO', true);
INSERT INTO sujeto.profesion (codigo, nombre, activo) VALUES ('448', 'MECANNICO HELICOPTEROS', true);
INSERT INTO sujeto.profesion (codigo, nombre, activo) VALUES ('449', 'MECANOGRAFO', true);
INSERT INTO sujeto.profesion (codigo, nombre, activo) VALUES ('45', 'APARADOR DE CALZADO', true);
INSERT INTO sujeto.profesion (codigo, nombre, activo) VALUES ('450', 'MEDICO', true);
INSERT INTO sujeto.profesion (codigo, nombre, activo) VALUES ('451', 'MEDICO VETERINARIO', true);
INSERT INTO sujeto.profesion (codigo, nombre, activo) VALUES ('452', 'MENSAJERO', true);
INSERT INTO sujeto.profesion (codigo, nombre, activo) VALUES ('453', 'MESERO', true);
INSERT INTO sujeto.profesion (codigo, nombre, activo) VALUES ('454', 'METALURGICO', true);
INSERT INTO sujeto.profesion (codigo, nombre, activo) VALUES ('455', 'METEREOLOGO', true);
INSERT INTO sujeto.profesion (codigo, nombre, activo) VALUES ('456', 'MILITAR', true);
INSERT INTO sujeto.profesion (codigo, nombre, activo) VALUES ('457', 'MILITAR EN SERVICIO PASIVO', true);
INSERT INTO sujeto.profesion (codigo, nombre, activo) VALUES ('458', 'MIMIOGRAFISTA', true);
INSERT INTO sujeto.profesion (codigo, nombre, activo) VALUES ('459', 'MINERO', true);
INSERT INTO sujeto.profesion (codigo, nombre, activo) VALUES ('46', 'APICULTOR', true);
INSERT INTO sujeto.profesion (codigo, nombre, activo) VALUES ('460', 'MISIONERO', true);
INSERT INTO sujeto.profesion (codigo, nombre, activo) VALUES ('461', 'MODELADOR', true);
INSERT INTO sujeto.profesion (codigo, nombre, activo) VALUES ('462', 'MODELO', true);
INSERT INTO sujeto.profesion (codigo, nombre, activo) VALUES ('463', 'MODISTA', true);
INSERT INTO sujeto.profesion (codigo, nombre, activo) VALUES ('464', 'MOLDEADOR', true);
INSERT INTO sujeto.profesion (codigo, nombre, activo) VALUES ('465', 'MOLINERO', true);
INSERT INTO sujeto.profesion (codigo, nombre, activo) VALUES ('466', 'MONJA', true);
INSERT INTO sujeto.profesion (codigo, nombre, activo) VALUES ('467', 'MOTONIVELADOR', true);
INSERT INTO sujeto.profesion (codigo, nombre, activo) VALUES ('468', 'MOTORISTA', true);
INSERT INTO sujeto.profesion (codigo, nombre, activo) VALUES ('469', 'MOZO RESTAURANTE', true);
INSERT INTO sujeto.profesion (codigo, nombre, activo) VALUES ('47', 'APLANCHADORA', true);
INSERT INTO sujeto.profesion (codigo, nombre, activo) VALUES ('470', 'MUEBLISTA', true);
INSERT INTO sujeto.profesion (codigo, nombre, activo) VALUES ('471', 'MUSEOLOGO/S', true);
INSERT INTO sujeto.profesion (codigo, nombre, activo) VALUES ('472', 'MUSICO', true);
INSERT INTO sujeto.profesion (codigo, nombre, activo) VALUES ('473', 'NATURALISTA', true);
INSERT INTO sujeto.profesion (codigo, nombre, activo) VALUES ('474', 'NAVEG. AVIACION', true);
INSERT INTO sujeto.profesion (codigo, nombre, activo) VALUES ('475', 'NEGOCIANTE', true);
INSERT INTO sujeto.profesion (codigo, nombre, activo) VALUES ('477', 'NIQUELADOR', true);
INSERT INTO sujeto.profesion (codigo, nombre, activo) VALUES ('478', 'NIVELADOR', true);
INSERT INTO sujeto.profesion (codigo, nombre, activo) VALUES ('479', 'NIÑERA', true);
INSERT INTO sujeto.profesion (codigo, nombre, activo) VALUES ('48', 'APODERADO', true);
INSERT INTO sujeto.profesion (codigo, nombre, activo) VALUES ('480', 'NOTARIO', true);
INSERT INTO sujeto.profesion (codigo, nombre, activo) VALUES ('481', 'OBRERO', true);
INSERT INTO sujeto.profesion (codigo, nombre, activo) VALUES ('482', 'OBSTETRIZ', true);
INSERT INTO sujeto.profesion (codigo, nombre, activo) VALUES ('483', 'OCULISTA', true);
INSERT INTO sujeto.profesion (codigo, nombre, activo) VALUES ('484', 'ODONTOLOGO', true);
INSERT INTO sujeto.profesion (codigo, nombre, activo) VALUES ('485', 'OFICIAL DE BOMBEROS', true);
INSERT INTO sujeto.profesion (codigo, nombre, activo) VALUES ('486', 'OFICINISTA', true);
INSERT INTO sujeto.profesion (codigo, nombre, activo) VALUES ('487', 'OPERADOR', true);
INSERT INTO sujeto.profesion (codigo, nombre, activo) VALUES ('488', 'OPERADOR DE SISTEMAS', true);
INSERT INTO sujeto.profesion (codigo, nombre, activo) VALUES ('489', 'OPERADOR EQUIPO PESADO', true);
INSERT INTO sujeto.profesion (codigo, nombre, activo) VALUES ('49', 'APRENDIZ', true);
INSERT INTO sujeto.profesion (codigo, nombre, activo) VALUES ('490', 'OPERADOR MAQUINA AGRICOLAS', true);
INSERT INTO sujeto.profesion (codigo, nombre, activo) VALUES ('491', 'OPERARIO', true);
INSERT INTO sujeto.profesion (codigo, nombre, activo) VALUES ('492', 'OPTALMOLOGO', true);
INSERT INTO sujeto.profesion (codigo, nombre, activo) VALUES ('493', 'OPTICO', true);
INSERT INTO sujeto.profesion (codigo, nombre, activo) VALUES ('494', 'OPTOMETRISTA', true);
INSERT INTO sujeto.profesion (codigo, nombre, activo) VALUES ('495', 'ORDENADOR', true);
INSERT INTO sujeto.profesion (codigo, nombre, activo) VALUES ('496', 'ORFEBRE', true);
INSERT INTO sujeto.profesion (codigo, nombre, activo) VALUES ('497', 'ORIENTADOR VOCACIONAL PROFESOR', true);
INSERT INTO sujeto.profesion (codigo, nombre, activo) VALUES ('498', 'ORTOPEDICO', true);
INSERT INTO sujeto.profesion (codigo, nombre, activo) VALUES ('499', 'OVICULTOR', true);
INSERT INTO sujeto.profesion (codigo, nombre, activo) VALUES ('5', 'ACROBATA', true);
INSERT INTO sujeto.profesion (codigo, nombre, activo) VALUES ('50', 'APURADOR', true);
INSERT INTO sujeto.profesion (codigo, nombre, activo) VALUES ('500', 'OTRAS ACTIVIDADES', true);
INSERT INTO sujeto.profesion (codigo, nombre, activo) VALUES ('501', 'PAGADOR', true);
INSERT INTO sujeto.profesion (codigo, nombre, activo) VALUES ('502', 'PAILERO', true);
INSERT INTO sujeto.profesion (codigo, nombre, activo) VALUES ('503', 'PALEOLOGO', true);
INSERT INTO sujeto.profesion (codigo, nombre, activo) VALUES ('504', 'PALEONTOLOGO', true);
INSERT INTO sujeto.profesion (codigo, nombre, activo) VALUES ('505', 'PANADERO', true);
INSERT INTO sujeto.profesion (codigo, nombre, activo) VALUES ('506', 'PANTALONERO', true);
INSERT INTO sujeto.profesion (codigo, nombre, activo) VALUES ('507', 'PARTERA', true);
INSERT INTO sujeto.profesion (codigo, nombre, activo) VALUES ('508', 'PASTELERO', true);
INSERT INTO sujeto.profesion (codigo, nombre, activo) VALUES ('509', 'PASTOR', true);
INSERT INTO sujeto.profesion (codigo, nombre, activo) VALUES ('51', 'ARBITRO', true);
INSERT INTO sujeto.profesion (codigo, nombre, activo) VALUES ('510', 'PATRON COSTANERO', true);
INSERT INTO sujeto.profesion (codigo, nombre, activo) VALUES ('511', 'PEDICURISTA', true);
INSERT INTO sujeto.profesion (codigo, nombre, activo) VALUES ('512', 'PEINADOR', true);
INSERT INTO sujeto.profesion (codigo, nombre, activo) VALUES ('513', 'PELETERO', true);
INSERT INTO sujeto.profesion (codigo, nombre, activo) VALUES ('514', 'PELUQUERO', true);
INSERT INTO sujeto.profesion (codigo, nombre, activo) VALUES ('515', 'PEON', true);
INSERT INTO sujeto.profesion (codigo, nombre, activo) VALUES ('516', 'PEQUEÑO INDUSTRIAL', true);
INSERT INTO sujeto.profesion (codigo, nombre, activo) VALUES ('517', 'PERFORADOR', true);
INSERT INTO sujeto.profesion (codigo, nombre, activo) VALUES ('518', 'PERIODISTA', true);
INSERT INTO sujeto.profesion (codigo, nombre, activo) VALUES ('519', 'PERITO', true);
INSERT INTO sujeto.profesion (codigo, nombre, activo) VALUES ('52', 'ARCHIVERO', true);
INSERT INTO sujeto.profesion (codigo, nombre, activo) VALUES ('520', 'PERITO ELECTRICISTA', true);
INSERT INTO sujeto.profesion (codigo, nombre, activo) VALUES ('521', 'PERITO FORESTAL', true);
INSERT INTO sujeto.profesion (codigo, nombre, activo) VALUES ('522', 'PERITO GEOMENSOR', true);
INSERT INTO sujeto.profesion (codigo, nombre, activo) VALUES ('523', 'PESCADOR', true);
INSERT INTO sujeto.profesion (codigo, nombre, activo) VALUES ('524', 'PETROLERO', true);
INSERT INTO sujeto.profesion (codigo, nombre, activo) VALUES ('525', 'PH. D CC. TECNICAS', true);
INSERT INTO sujeto.profesion (codigo, nombre, activo) VALUES ('526', 'PH. D EN QUIMICA', true);
INSERT INTO sujeto.profesion (codigo, nombre, activo) VALUES ('527', 'PICADORES', true);
INSERT INTO sujeto.profesion (codigo, nombre, activo) VALUES ('528', 'PICAPEDRERO', true);
INSERT INTO sujeto.profesion (codigo, nombre, activo) VALUES ('529', 'PILOTO', true);
INSERT INTO sujeto.profesion (codigo, nombre, activo) VALUES ('53', 'ARQUEOLOGO', true);
INSERT INTO sujeto.profesion (codigo, nombre, activo) VALUES ('530', 'PILOTO HELICOPTEROS', true);
INSERT INTO sujeto.profesion (codigo, nombre, activo) VALUES ('531', 'PINTOR', true);
INSERT INTO sujeto.profesion (codigo, nombre, activo) VALUES ('532', 'PINTOR ESCULTOR', true);
INSERT INTO sujeto.profesion (codigo, nombre, activo) VALUES ('533', 'PIROTECNICO', true);
INSERT INTO sujeto.profesion (codigo, nombre, activo) VALUES ('534', 'PISCICULTOR', true);
INSERT INTO sujeto.profesion (codigo, nombre, activo) VALUES ('535', 'PLANCHADOR', true);
INSERT INTO sujeto.profesion (codigo, nombre, activo) VALUES ('536', 'PLANTADOR', true);
INSERT INTO sujeto.profesion (codigo, nombre, activo) VALUES ('537', 'PLATERO', true);
INSERT INTO sujeto.profesion (codigo, nombre, activo) VALUES ('538', 'PLENIPOTENCIARIO', true);
INSERT INTO sujeto.profesion (codigo, nombre, activo) VALUES ('539', 'PLOMERO', true);
INSERT INTO sujeto.profesion (codigo, nombre, activo) VALUES ('54', 'ARQUITECTO', true);
INSERT INTO sujeto.profesion (codigo, nombre, activo) VALUES ('540', 'POLICIA', true);
INSERT INTO sujeto.profesion (codigo, nombre, activo) VALUES ('541', 'POLICIA ADUANERO', true);
INSERT INTO sujeto.profesion (codigo, nombre, activo) VALUES ('542', 'POLICIA JUDICIAL', true);
INSERT INTO sujeto.profesion (codigo, nombre, activo) VALUES ('543', 'POLICIA MUNICIPAL', true);
INSERT INTO sujeto.profesion (codigo, nombre, activo) VALUES ('544', 'POLICIA SERVICIO PASIVO', true);
INSERT INTO sujeto.profesion (codigo, nombre, activo) VALUES ('545', 'PORTERO', true);
INSERT INTO sujeto.profesion (codigo, nombre, activo) VALUES ('546', 'POSILLERO', true);
INSERT INTO sujeto.profesion (codigo, nombre, activo) VALUES ('547', 'POSTILLON', true);
INSERT INTO sujeto.profesion (codigo, nombre, activo) VALUES ('548', 'PRACTICO AGRICOLA', true);
INSERT INTO sujeto.profesion (codigo, nombre, activo) VALUES ('549', 'PRECEPTOR', true);
INSERT INTO sujeto.profesion (codigo, nombre, activo) VALUES ('55', 'ARRIERO', true);
INSERT INTO sujeto.profesion (codigo, nombre, activo) VALUES ('550', 'PRENSISTA', true);
INSERT INTO sujeto.profesion (codigo, nombre, activo) VALUES ('551', 'PRESBITERO', true);
INSERT INTO sujeto.profesion (codigo, nombre, activo) VALUES ('552', 'PRESTAMISTA', true);
INSERT INTO sujeto.profesion (codigo, nombre, activo) VALUES ('553', 'PROCURADOR', true);
INSERT INTO sujeto.profesion (codigo, nombre, activo) VALUES ('554', 'PRODUCTOR', true);
INSERT INTO sujeto.profesion (codigo, nombre, activo) VALUES ('555', 'PRODUCTOR T.V.', true);
INSERT INTO sujeto.profesion (codigo, nombre, activo) VALUES ('556', 'PROFESIONAL EN GENERAL', true);
INSERT INTO sujeto.profesion (codigo, nombre, activo) VALUES ('557', 'PROFESOR', true);
INSERT INTO sujeto.profesion (codigo, nombre, activo) VALUES ('558', 'PROFESOR EN GENERAL', true);
INSERT INTO sujeto.profesion (codigo, nombre, activo) VALUES ('559', 'PROGRAMADOR DE COMPUTADOR', true);
INSERT INTO sujeto.profesion (codigo, nombre, activo) VALUES ('56', 'ARTESANO', true);
INSERT INTO sujeto.profesion (codigo, nombre, activo) VALUES ('560', 'PROMOTOR Â COMERCIO EXTRANJERO', true);
INSERT INTO sujeto.profesion (codigo, nombre, activo) VALUES ('561', 'PROVEEDOR', true);
INSERT INTO sujeto.profesion (codigo, nombre, activo) VALUES ('562', 'PROYECTISTA', true);
INSERT INTO sujeto.profesion (codigo, nombre, activo) VALUES ('563', 'PSICOLOGO', true);
INSERT INTO sujeto.profesion (codigo, nombre, activo) VALUES ('564', 'PSICOLOGO CLINICO', true);
INSERT INTO sujeto.profesion (codigo, nombre, activo) VALUES ('565', 'PSIQUIATRA', true);
INSERT INTO sujeto.profesion (codigo, nombre, activo) VALUES ('566', 'PUBLICISTA', true);
INSERT INTO sujeto.profesion (codigo, nombre, activo) VALUES ('567', 'PULIDOR', true);
INSERT INTO sujeto.profesion (codigo, nombre, activo) VALUES ('568', 'QUEHACERES DOMESTICOS', true);
INSERT INTO sujeto.profesion (codigo, nombre, activo) VALUES ('569', 'QUESERO', true);
INSERT INTO sujeto.profesion (codigo, nombre, activo) VALUES ('57', 'ARTISTA PROF ', true);
INSERT INTO sujeto.profesion (codigo, nombre, activo) VALUES ('570', 'QUIMICO FARMACEUTICO', true);
INSERT INTO sujeto.profesion (codigo, nombre, activo) VALUES ('571', 'QUIROGRAFO', true);
INSERT INTO sujeto.profesion (codigo, nombre, activo) VALUES ('572', 'QUIROPEDISTA', true);
INSERT INTO sujeto.profesion (codigo, nombre, activo) VALUES ('573', 'QUMICO', true);
INSERT INTO sujeto.profesion (codigo, nombre, activo) VALUES ('574', 'RADIODIFUSOR', true);
INSERT INTO sujeto.profesion (codigo, nombre, activo) VALUES ('575', 'RADIOLOGO', true);
INSERT INTO sujeto.profesion (codigo, nombre, activo) VALUES ('576', 'RADIOPERADOR', true);
INSERT INTO sujeto.profesion (codigo, nombre, activo) VALUES ('577', 'RADIOTECNICO', true);
INSERT INTO sujeto.profesion (codigo, nombre, activo) VALUES ('578', 'RADIOTELEFONISTA', true);
INSERT INTO sujeto.profesion (codigo, nombre, activo) VALUES ('579', 'RADIOTELEGRAFISTA', true);
INSERT INTO sujeto.profesion (codigo, nombre, activo) VALUES ('58', 'ASCENSORISTA', true);
INSERT INTO sujeto.profesion (codigo, nombre, activo) VALUES ('580', 'RECAUDADOR', true);
INSERT INTO sujeto.profesion (codigo, nombre, activo) VALUES ('581', 'RECAUDADOR R. TELEF.', true);
INSERT INTO sujeto.profesion (codigo, nombre, activo) VALUES ('582', 'RECEPCIONISTA', true);
INSERT INTO sujeto.profesion (codigo, nombre, activo) VALUES ('583', 'RECORREDOR', true);
INSERT INTO sujeto.profesion (codigo, nombre, activo) VALUES ('584', 'REDACTOR', true);
INSERT INTO sujeto.profesion (codigo, nombre, activo) VALUES ('585', 'REGENTE', true);
INSERT INTO sujeto.profesion (codigo, nombre, activo) VALUES ('586', 'REGISTRADOR', true);
INSERT INTO sujeto.profesion (codigo, nombre, activo) VALUES ('587', 'RELACIONISTA', true);
INSERT INTO sujeto.profesion (codigo, nombre, activo) VALUES ('588', 'RELIGIOSO', true);
INSERT INTO sujeto.profesion (codigo, nombre, activo) VALUES ('589', 'RELOJERO', true);
INSERT INTO sujeto.profesion (codigo, nombre, activo) VALUES ('59', 'ASERRADOR', true);
INSERT INTO sujeto.profesion (codigo, nombre, activo) VALUES ('590', 'REMACHADOR', true);
INSERT INTO sujeto.profesion (codigo, nombre, activo) VALUES ('591', 'REMALLADOR', true);
INSERT INTO sujeto.profesion (codigo, nombre, activo) VALUES ('592', 'REMATADOR', true);
INSERT INTO sujeto.profesion (codigo, nombre, activo) VALUES ('593', 'RENTISTA', true);
INSERT INTO sujeto.profesion (codigo, nombre, activo) VALUES ('594', 'REPARADOR', true);
INSERT INTO sujeto.profesion (codigo, nombre, activo) VALUES ('595', 'REPARTIDOR', true);
INSERT INTO sujeto.profesion (codigo, nombre, activo) VALUES ('596', 'REPORTERO', true);
INSERT INTO sujeto.profesion (codigo, nombre, activo) VALUES ('597', 'REPORTERO GRAFICO', true);
INSERT INTO sujeto.profesion (codigo, nombre, activo) VALUES ('598', 'REPOSTERO', true);
INSERT INTO sujeto.profesion (codigo, nombre, activo) VALUES ('599', 'REPRESENTANTE', true);
INSERT INTO sujeto.profesion (codigo, nombre, activo) VALUES ('6', 'ACTOR', true);
INSERT INTO sujeto.profesion (codigo, nombre, activo) VALUES ('60', 'ASESOR', true);
INSERT INTO sujeto.profesion (codigo, nombre, activo) VALUES ('600', 'REPRESENTANTE DE VENTAS', true);
INSERT INTO sujeto.profesion (codigo, nombre, activo) VALUES ('601', 'REPRESENTANTE OBRAS DE ARTE', true);
INSERT INTO sujeto.profesion (codigo, nombre, activo) VALUES ('602', 'RETIRADO', true);
INSERT INTO sujeto.profesion (codigo, nombre, activo) VALUES ('603', 'RETOCADOR', true);
INSERT INTO sujeto.profesion (codigo, nombre, activo) VALUES ('604', 'ROTOGRABADOR', true);
INSERT INTO sujeto.profesion (codigo, nombre, activo) VALUES ('605', 'ROTULADOR', true);
INSERT INTO sujeto.profesion (codigo, nombre, activo) VALUES ('606', 'SACERDOTE', true);
INSERT INTO sujeto.profesion (codigo, nombre, activo) VALUES ('607', 'SACRISTAN', true);
INSERT INTO sujeto.profesion (codigo, nombre, activo) VALUES ('608', 'SALONERO', true);
INSERT INTO sujeto.profesion (codigo, nombre, activo) VALUES ('609', 'SASTRE', true);
INSERT INTO sujeto.profesion (codigo, nombre, activo) VALUES ('61', 'ASISTENTE', true);
INSERT INTO sujeto.profesion (codigo, nombre, activo) VALUES ('610', 'SECRETARIO/A', true);
INSERT INTO sujeto.profesion (codigo, nombre, activo) VALUES ('611', 'SECRETARIO/A BILINGUE', true);
INSERT INTO sujeto.profesion (codigo, nombre, activo) VALUES ('612', 'SECRETARIO/A EJECUTIVO/A', true);
INSERT INTO sujeto.profesion (codigo, nombre, activo) VALUES ('613', 'SELLADOR', true);
INSERT INTO sujeto.profesion (codigo, nombre, activo) VALUES ('614', 'SERIGNOFISTA', true);
INSERT INTO sujeto.profesion (codigo, nombre, activo) VALUES ('615', 'SERIGRAFO', true);
INSERT INTO sujeto.profesion (codigo, nombre, activo) VALUES ('616', 'SERISCICULTOR', true);
INSERT INTO sujeto.profesion (codigo, nombre, activo) VALUES ('617', 'SERVICULTOR', true);
INSERT INTO sujeto.profesion (codigo, nombre, activo) VALUES ('618', 'SIFONERO', true);
INSERT INTO sujeto.profesion (codigo, nombre, activo) VALUES ('619', 'SINDICO', true);
INSERT INTO sujeto.profesion (codigo, nombre, activo) VALUES ('62', 'ASISTENTE GERENCIA', true);
INSERT INTO sujeto.profesion (codigo, nombre, activo) VALUES ('620', 'SIRVIENTE', true);
INSERT INTO sujeto.profesion (codigo, nombre, activo) VALUES ('621', 'SOBRESTANTE', true);
INSERT INTO sujeto.profesion (codigo, nombre, activo) VALUES ('622', 'SOCIOLOGO', true);
INSERT INTO sujeto.profesion (codigo, nombre, activo) VALUES ('623', 'SOGUERO', true);
INSERT INTO sujeto.profesion (codigo, nombre, activo) VALUES ('624', 'SOLDADOR', true);
INSERT INTO sujeto.profesion (codigo, nombre, activo) VALUES ('625', 'SOMBRERERO', true);
INSERT INTO sujeto.profesion (codigo, nombre, activo) VALUES ('626', 'SPULTURERO', true);
INSERT INTO sujeto.profesion (codigo, nombre, activo) VALUES ('627', 'SR. EN OPTOMETRIA', true);
INSERT INTO sujeto.profesion (codigo, nombre, activo) VALUES ('628', 'SUBASTADOR', true);
INSERT INTO sujeto.profesion (codigo, nombre, activo) VALUES ('629', 'SUPERVISOR', true);
INSERT INTO sujeto.profesion (codigo, nombre, activo) VALUES ('63', 'ASISTENTE PEDIATRIA', true);
INSERT INTO sujeto.profesion (codigo, nombre, activo) VALUES ('630', 'TABACALERO', true);
INSERT INTO sujeto.profesion (codigo, nombre, activo) VALUES ('631', 'TABERNERO', true);
INSERT INTO sujeto.profesion (codigo, nombre, activo) VALUES ('632', 'TALABARTERO', true);
INSERT INTO sujeto.profesion (codigo, nombre, activo) VALUES ('633', 'TALLADOR', true);
INSERT INTO sujeto.profesion (codigo, nombre, activo) VALUES ('634', 'TAMIGRAFO', true);
INSERT INTO sujeto.profesion (codigo, nombre, activo) VALUES ('635', 'TAPIZADOR', true);
INSERT INTO sujeto.profesion (codigo, nombre, activo) VALUES ('636', 'TAQUIGRAFO', true);
INSERT INTO sujeto.profesion (codigo, nombre, activo) VALUES ('637', 'TAQUIMECANOGRAFO/A', true);
INSERT INTO sujeto.profesion (codigo, nombre, activo) VALUES ('638', 'TAXIDERMISTA', true);
INSERT INTO sujeto.profesion (codigo, nombre, activo) VALUES ('639', 'TCNL. COMUNICACIONES', true);
INSERT INTO sujeto.profesion (codigo, nombre, activo) VALUES ('64', 'ASTRONOMO', true);
INSERT INTO sujeto.profesion (codigo, nombre, activo) VALUES ('640', 'TCNL. CONSTRUCCION CIVIL', true);
INSERT INTO sujeto.profesion (codigo, nombre, activo) VALUES ('641', 'TCNL. COOP. TRANSITO', true);
INSERT INTO sujeto.profesion (codigo, nombre, activo) VALUES ('642', 'TCNL. COSTOS INDUTRIAL.', true);
INSERT INTO sujeto.profesion (codigo, nombre, activo) VALUES ('643', 'TCNL. DISEÑADOR INTERIOR', true);
INSERT INTO sujeto.profesion (codigo, nombre, activo) VALUES ('644', 'TCNL. ELECTROMECANICO', true);
INSERT INTO sujeto.profesion (codigo, nombre, activo) VALUES ('645', 'TCNL. MANTENIMIENTO INDUSTRIAL', true);
INSERT INTO sujeto.profesion (codigo, nombre, activo) VALUES ('646', 'TCNL. TERAP. LENGUAJE', true);
INSERT INTO sujeto.profesion (codigo, nombre, activo) VALUES ('647', 'TEC. INSTRUMENTA. QUIRURGICA', true);
INSERT INTO sujeto.profesion (codigo, nombre, activo) VALUES ('648', 'TEC. MECANICO INDUSTRIAL', true);
INSERT INTO sujeto.profesion (codigo, nombre, activo) VALUES ('649', 'TEC. SUP. ADMINIS. FINCAS', true);
INSERT INTO sujeto.profesion (codigo, nombre, activo) VALUES ('65', 'ATLETA', true);
INSERT INTO sujeto.profesion (codigo, nombre, activo) VALUES ('650', 'TEC. SUP. MECANICO AUTOMOTRIZ', true);
INSERT INTO sujeto.profesion (codigo, nombre, activo) VALUES ('651', 'TEC. SUP. NUTRICION ANIMAL', true);
INSERT INTO sujeto.profesion (codigo, nombre, activo) VALUES ('652', 'TEC. SUP. OPTOMETRIA', true);
INSERT INTO sujeto.profesion (codigo, nombre, activo) VALUES ('653', 'TECNICO', true);
INSERT INTO sujeto.profesion (codigo, nombre, activo) VALUES ('654', 'TECNICO AGRONOMO', true);
INSERT INTO sujeto.profesion (codigo, nombre, activo) VALUES ('655', 'TECNICO AGROPECUARIO', true);
INSERT INTO sujeto.profesion (codigo, nombre, activo) VALUES ('656', 'TECNICO ANALISTA DE SISTEMAS', true);
INSERT INTO sujeto.profesion (codigo, nombre, activo) VALUES ('657', 'TECNICO AUTOMOTRIZ', true);
INSERT INTO sujeto.profesion (codigo, nombre, activo) VALUES ('658', 'TECNICO CONSTRUCCION', true);
INSERT INTO sujeto.profesion (codigo, nombre, activo) VALUES ('659', 'TECNICO CRIPTOGRAFICO', true);
INSERT INTO sujeto.profesion (codigo, nombre, activo) VALUES ('66', 'AUDITOR', true);
INSERT INTO sujeto.profesion (codigo, nombre, activo) VALUES ('660', 'TECNICO ELECTRICISTA', true);
INSERT INTO sujeto.profesion (codigo, nombre, activo) VALUES ('661', 'TECNICO ELECTRONICA', true);
INSERT INTO sujeto.profesion (codigo, nombre, activo) VALUES ('662', 'TECNICO EN LECHERIA', true);
INSERT INTO sujeto.profesion (codigo, nombre, activo) VALUES ('663', 'TECNICO EN REFRIGERACION', true);
INSERT INTO sujeto.profesion (codigo, nombre, activo) VALUES ('664', 'TECNICO EN SEGUROS', true);
INSERT INTO sujeto.profesion (codigo, nombre, activo) VALUES ('665', 'TECNICO EN TURISMO', true);
INSERT INTO sujeto.profesion (codigo, nombre, activo) VALUES ('666', 'TECNICO MATRICERO', true);
INSERT INTO sujeto.profesion (codigo, nombre, activo) VALUES ('667', 'TECNICO OPERADOR DE VUELO', true);
INSERT INTO sujeto.profesion (codigo, nombre, activo) VALUES ('668', 'TECNICO REDES TELEFONICAS', true);
INSERT INTO sujeto.profesion (codigo, nombre, activo) VALUES ('669', 'TECNICO TEXTIL', true);
INSERT INTO sujeto.profesion (codigo, nombre, activo) VALUES ('67', 'AUTOMETRISTA', true);
INSERT INTO sujeto.profesion (codigo, nombre, activo) VALUES ('670', 'TECNOGOLO EN PETROLEOS', true);
INSERT INTO sujeto.profesion (codigo, nombre, activo) VALUES ('671', 'TECNOLOGO', true);
INSERT INTO sujeto.profesion (codigo, nombre, activo) VALUES ('672', 'TECNOLOGO ELECTRICO', true);
INSERT INTO sujeto.profesion (codigo, nombre, activo) VALUES ('673', 'TECNOLOGO ELECTRONICO', true);
INSERT INTO sujeto.profesion (codigo, nombre, activo) VALUES ('674', 'TECNOLOGO EN COMPUTACION', true);
INSERT INTO sujeto.profesion (codigo, nombre, activo) VALUES ('675', 'TECNOLOGO EN MINAS', true);
INSERT INTO sujeto.profesion (codigo, nombre, activo) VALUES ('676', 'TECNOLOGO EN RECREA. INFANTIL', true);
INSERT INTO sujeto.profesion (codigo, nombre, activo) VALUES ('677', 'TECNOLOGO INDUSTRIAL', true);
INSERT INTO sujeto.profesion (codigo, nombre, activo) VALUES ('678', 'TECNOLOGO MECANICO', true);
INSERT INTO sujeto.profesion (codigo, nombre, activo) VALUES ('679', 'TECNOLOGO MEDICO', true);
INSERT INTO sujeto.profesion (codigo, nombre, activo) VALUES ('68', 'AUTOR', true);
INSERT INTO sujeto.profesion (codigo, nombre, activo) VALUES ('680', 'TEJEDOR', true);
INSERT INTO sujeto.profesion (codigo, nombre, activo) VALUES ('681', 'TELEFONISTA', true);
INSERT INTO sujeto.profesion (codigo, nombre, activo) VALUES ('682', 'TELEGRAFISTA', true);
INSERT INTO sujeto.profesion (codigo, nombre, activo) VALUES ('683', 'TELEPATA', true);
INSERT INTO sujeto.profesion (codigo, nombre, activo) VALUES ('684', 'TERAPEUTA', true);
INSERT INTO sujeto.profesion (codigo, nombre, activo) VALUES ('685', 'TERAPISTA EN LEGUAJE', true);
INSERT INTO sujeto.profesion (codigo, nombre, activo) VALUES ('686', 'TERAPISTA OCUPACIONAL', true);
INSERT INTO sujeto.profesion (codigo, nombre, activo) VALUES ('687', 'TERCENISTA', true);
INSERT INTO sujeto.profesion (codigo, nombre, activo) VALUES ('688', 'TESORERO', true);
INSERT INTO sujeto.profesion (codigo, nombre, activo) VALUES ('689', 'TEÑIDOR', true);
INSERT INTO sujeto.profesion (codigo, nombre, activo) VALUES ('69', 'AUTOR COMPOSITOR', true);
INSERT INTO sujeto.profesion (codigo, nombre, activo) VALUES ('690', 'TINTORERO', true);
INSERT INTO sujeto.profesion (codigo, nombre, activo) VALUES ('691', 'TIPOGRAFO', true);
INSERT INTO sujeto.profesion (codigo, nombre, activo) VALUES ('692', 'TOPOLOGO', true);
INSERT INTO sujeto.profesion (codigo, nombre, activo) VALUES ('693', 'TOQUILLERO', true);
INSERT INTO sujeto.profesion (codigo, nombre, activo) VALUES ('694', 'TORERO', true);
INSERT INTO sujeto.profesion (codigo, nombre, activo) VALUES ('695', 'TORNERO', true);
INSERT INTO sujeto.profesion (codigo, nombre, activo) VALUES ('696', 'TRABAJADOR', true);
INSERT INTO sujeto.profesion (codigo, nombre, activo) VALUES ('697', 'TRABAJADOR SOCIAL', true);
INSERT INTO sujeto.profesion (codigo, nombre, activo) VALUES ('698', 'TRACTORISTA', true);
INSERT INTO sujeto.profesion (codigo, nombre, activo) VALUES ('699', 'TRADUCTOR', true);
INSERT INTO sujeto.profesion (codigo, nombre, activo) VALUES ('7', 'ACTRIZ', true);
INSERT INTO sujeto.profesion (codigo, nombre, activo) VALUES ('70', 'AUXILIAR', true);
INSERT INTO sujeto.profesion (codigo, nombre, activo) VALUES ('700', 'TRAMOYISTA', true);
INSERT INTO sujeto.profesion (codigo, nombre, activo) VALUES ('701', 'TRANSMISOR', true);
INSERT INTO sujeto.profesion (codigo, nombre, activo) VALUES ('702', 'TRIPULANTE', true);
INSERT INTO sujeto.profesion (codigo, nombre, activo) VALUES ('703', 'VACUNADOR', true);
INSERT INTO sujeto.profesion (codigo, nombre, activo) VALUES ('704', 'VAQUERO', true);
INSERT INTO sujeto.profesion (codigo, nombre, activo) VALUES ('705', 'VELADOR', true);
INSERT INTO sujeto.profesion (codigo, nombre, activo) VALUES ('706', 'VENDEDOR', true);
INSERT INTO sujeto.profesion (codigo, nombre, activo) VALUES ('707', 'VETERINARIO', true);
INSERT INTO sujeto.profesion (codigo, nombre, activo) VALUES ('708', 'VIDRIERO', true);
INSERT INTO sujeto.profesion (codigo, nombre, activo) VALUES ('709', 'VIGILANTE', true);
INSERT INTO sujeto.profesion (codigo, nombre, activo) VALUES ('71', 'AUXILIAR DE CONTABILIDAD', true);
INSERT INTO sujeto.profesion (codigo, nombre, activo) VALUES ('710', 'VINICULTOR', true);
INSERT INTO sujeto.profesion (codigo, nombre, activo) VALUES ('711', 'VISITADOR MEDICO', true);
INSERT INTO sujeto.profesion (codigo, nombre, activo) VALUES ('712', 'VISITADOR SOCIAL', true);
INSERT INTO sujeto.profesion (codigo, nombre, activo) VALUES ('713', 'VITICULTOR', true);
INSERT INTO sujeto.profesion (codigo, nombre, activo) VALUES ('714', 'VIVANDERA', true);
INSERT INTO sujeto.profesion (codigo, nombre, activo) VALUES ('715', 'VOCEADOR', true);
INSERT INTO sujeto.profesion (codigo, nombre, activo) VALUES ('716', 'VULCANIZADOR', true);
INSERT INTO sujeto.profesion (codigo, nombre, activo) VALUES ('717', 'XILOGRAFO', true);
INSERT INTO sujeto.profesion (codigo, nombre, activo) VALUES ('718', 'YESERO', true);
INSERT INTO sujeto.profesion (codigo, nombre, activo) VALUES ('719', 'ZAPATERO', true);
INSERT INTO sujeto.profesion (codigo, nombre, activo) VALUES ('72', 'AUXILIAR ENFERMERIA', true);
INSERT INTO sujeto.profesion (codigo, nombre, activo) VALUES ('720', 'ZOOLOGO', true);
INSERT INTO sujeto.profesion (codigo, nombre, activo) VALUES ('721', 'ZOOTECNICO', true);
INSERT INTO sujeto.profesion (codigo, nombre, activo) VALUES ('722', 'ESPECIALISTA', true);
INSERT INTO sujeto.profesion (codigo, nombre, activo) VALUES ('723', 'BACHILLER EN CIENCIAS ', true);
INSERT INTO sujeto.profesion (codigo, nombre, activo) VALUES ('724', 'ALFERES DE FRAGATA', true);
INSERT INTO sujeto.profesion (codigo, nombre, activo) VALUES ('725', 'ALFERES DE NAVIO', true);
INSERT INTO sujeto.profesion (codigo, nombre, activo) VALUES ('726', 'AUXILIAR DE ODONTOLOGIA', true);
INSERT INTO sujeto.profesion (codigo, nombre, activo) VALUES ('727', 'CATEDRATICO', true);
INSERT INTO sujeto.profesion (codigo, nombre, activo) VALUES ('728', 'COORDINADOR', true);
INSERT INTO sujeto.profesion (codigo, nombre, activo) VALUES ('729', 'EJECUTIVO DE VENTAS', true);
INSERT INTO sujeto.profesion (codigo, nombre, activo) VALUES ('73', 'AUXILIAR SECRETARIA', true);
INSERT INTO sujeto.profesion (codigo, nombre, activo) VALUES ('730', 'FONOAUDIOLOGA', true);
INSERT INTO sujeto.profesion (codigo, nombre, activo) VALUES ('731', 'JEFE DE AGENCIA', true);
INSERT INTO sujeto.profesion (codigo, nombre, activo) VALUES ('732', 'JEFE DE BODEGA', true);
INSERT INTO sujeto.profesion (codigo, nombre, activo) VALUES ('733', 'JEFE DE SISTEMAS', true);
INSERT INTO sujeto.profesion (codigo, nombre, activo) VALUES ('734', 'SANEAMIENTO AMBIENTAL', true);
INSERT INTO sujeto.profesion (codigo, nombre, activo) VALUES ('735', 'TAXISTA', true);
INSERT INTO sujeto.profesion (codigo, nombre, activo) VALUES ('736', 'TECNICA EN MERCADOTECNIA', true);
INSERT INTO sujeto.profesion (codigo, nombre, activo) VALUES ('737', 'CLERIGO', true);
INSERT INTO sujeto.profesion (codigo, nombre, activo) VALUES ('738', 'BACHILLER QUIMICO BIOLOGO', true);
INSERT INTO sujeto.profesion (codigo, nombre, activo) VALUES ('739', 'MUSICO', true);
INSERT INTO sujeto.profesion (codigo, nombre, activo) VALUES ('74', 'AVALUADOR', true);
INSERT INTO sujeto.profesion (codigo, nombre, activo) VALUES ('740', 'BACHILLERATO SERVICIOS', true);
INSERT INTO sujeto.profesion (codigo, nombre, activo) VALUES ('741', 'MAESTRO DE CORTE Y CONFECCION', true);
INSERT INTO sujeto.profesion (codigo, nombre, activo) VALUES ('742', 'BACHILLER COMER ADM', true);
INSERT INTO sujeto.profesion (codigo, nombre, activo) VALUES ('743', 'BACHILLER FIS MATE', true);
INSERT INTO sujeto.profesion (codigo, nombre, activo) VALUES ('744', 'INDU MECA AUTOMOTRIZ', true);
INSERT INTO sujeto.profesion (codigo, nombre, activo) VALUES ('745', 'LUBRICADOR', true);
INSERT INTO sujeto.profesion (codigo, nombre, activo) VALUES ('746', 'BACHILLER ELECTROMECANICO', true);
INSERT INTO sujeto.profesion (codigo, nombre, activo) VALUES ('747', 'BACHILLER CC SOCIALES', true);
INSERT INTO sujeto.profesion (codigo, nombre, activo) VALUES ('748', 'TEC CONTABILIDAD ADMI', true);
INSERT INTO sujeto.profesion (codigo, nombre, activo) VALUES ('749', 'TEC POLIV CONT ADM', true);
INSERT INTO sujeto.profesion (codigo, nombre, activo) VALUES ('75', 'AVIADOR CIVIL', true);
INSERT INTO sujeto.profesion (codigo, nombre, activo) VALUES ('750', 'INFORMATICA', true);
INSERT INTO sujeto.profesion (codigo, nombre, activo) VALUES ('751', 'FUNCIONARIO PUBLICO', true);
INSERT INTO sujeto.profesion (codigo, nombre, activo) VALUES ('752', 'EMPLEADO PARTICULAR', true);
INSERT INTO sujeto.profesion (codigo, nombre, activo) VALUES ('753', 'BACH TEC SERV CONTAB', true);
INSERT INTO sujeto.profesion (codigo, nombre, activo) VALUES ('754', 'TECNICO SUPERIOR', true);
INSERT INTO sujeto.profesion (codigo, nombre, activo) VALUES ('755', 'LCDAD ATE PREH EMER', true);
INSERT INTO sujeto.profesion (codigo, nombre, activo) VALUES ('756', 'MODISTA', true);
INSERT INTO sujeto.profesion (codigo, nombre, activo) VALUES ('757', 'TEC INF ADM SISTEMAS', true);
INSERT INTO sujeto.profesion (codigo, nombre, activo) VALUES ('758', 'BACH TEC MECA INDUST', true);
INSERT INTO sujeto.profesion (codigo, nombre, activo) VALUES ('759', 'BACH TEC INDUS ELECT', true);
INSERT INTO sujeto.profesion (codigo, nombre, activo) VALUES ('76', 'AVIADOR COMERCIAL', true);
INSERT INTO sujeto.profesion (codigo, nombre, activo) VALUES ('760', 'BACH TEC CONTAB ADMI', true);
INSERT INTO sujeto.profesion (codigo, nombre, activo) VALUES ('761', 'BACH TEC MEC AUTOM', true);
INSERT INTO sujeto.profesion (codigo, nombre, activo) VALUES ('762', 'BACH TEC ELECTRICIDAD', true);
INSERT INTO sujeto.profesion (codigo, nombre, activo) VALUES ('763', 'AGRICULTOR', true);
INSERT INTO sujeto.profesion (codigo, nombre, activo) VALUES ('764', 'JOYERO', true);
INSERT INTO sujeto.profesion (codigo, nombre, activo) VALUES ('766', 'CONTADOR BACHILLER', true);
INSERT INTO sujeto.profesion (codigo, nombre, activo) VALUES ('767', 'ING AGROINDUSTRIAL', true);
INSERT INTO sujeto.profesion (codigo, nombre, activo) VALUES ('768', 'BACH TEC COMERCIO', true);
INSERT INTO sujeto.profesion (codigo, nombre, activo) VALUES ('769', 'BACH TEC COMERCIO ADMIN', true);
INSERT INTO sujeto.profesion (codigo, nombre, activo) VALUES ('77', 'AVIADOR MILITAR', true);
INSERT INTO sujeto.profesion (codigo, nombre, activo) VALUES ('770', 'BACH TEC POLIVAL ADM', true);
INSERT INTO sujeto.profesion (codigo, nombre, activo) VALUES ('771', 'BACH TEC POLIVAL INFOR', true);
INSERT INTO sujeto.profesion (codigo, nombre, activo) VALUES ('772', 'BACH GEST ADM CONTA', true);
INSERT INTO sujeto.profesion (codigo, nombre, activo) VALUES ('773', 'BACH  CIENCIAS GENERALES', true);
INSERT INTO sujeto.profesion (codigo, nombre, activo) VALUES ('774', 'LAS PERMI POR LA LEY', true);
INSERT INTO sujeto.profesion (codigo, nombre, activo) VALUES ('775', 'LIC GEST GASTRONOMIC', true);
INSERT INTO sujeto.profesion (codigo, nombre, activo) VALUES ('776', 'PROF EDUC PRIMARIA', true);
INSERT INTO sujeto.profesion (codigo, nombre, activo) VALUES ('778', 'DR PROMS EDUCA SALUD', true);
INSERT INTO sujeto.profesion (codigo, nombre, activo) VALUES ('779', 'BELLEZA Y PELUQUERIA', true);
INSERT INTO sujeto.profesion (codigo, nombre, activo) VALUES ('78', 'AVIADOR NAVAL', true);
INSERT INTO sujeto.profesion (codigo, nombre, activo) VALUES ('780', 'MASTER ADMINISTRACION', true);
INSERT INTO sujeto.profesion (codigo, nombre, activo) VALUES ('781', 'MAESTRO CONSTRUCCION', true);
INSERT INTO sujeto.profesion (codigo, nombre, activo) VALUES ('782', 'TLGO SUP ADM TURIST', true);
INSERT INTO sujeto.profesion (codigo, nombre, activo) VALUES ('783', 'ING MARKET GEST NEGO', true);
INSERT INTO sujeto.profesion (codigo, nombre, activo) VALUES ('784', 'TLGO ASIST GERENCIA', true);
INSERT INTO sujeto.profesion (codigo, nombre, activo) VALUES ('785', 'SALONERO', true);
INSERT INTO sujeto.profesion (codigo, nombre, activo) VALUES ('786', 'TECNICO', true);
INSERT INTO sujeto.profesion (codigo, nombre, activo) VALUES ('787', 'AGENTE VENDEDOR', true);
INSERT INTO sujeto.profesion (codigo, nombre, activo) VALUES ('789', 'BACH TEC AGROPECUAR', true);
INSERT INTO sujeto.profesion (codigo, nombre, activo) VALUES ('79', 'AVICULTOR', true);
INSERT INTO sujeto.profesion (codigo, nombre, activo) VALUES ('790', 'BACH TÉC SER APL I', true);
INSERT INTO sujeto.profesion (codigo, nombre, activo) VALUES ('791', 'BACH CC SOCIALES', true);
INSERT INTO sujeto.profesion (codigo, nombre, activo) VALUES ('792', 'BACH  CIENCIAS ', true);
INSERT INTO sujeto.profesion (codigo, nombre, activo) VALUES ('793', 'BACH TEC IND VESTIDO', true);
INSERT INTO sujeto.profesion (codigo, nombre, activo) VALUES ('794', 'BACHILLERATO INFORMATICO', true);
INSERT INTO sujeto.profesion (codigo, nombre, activo) VALUES ('795', 'BACH TECN ARTESANAL', true);
INSERT INTO sujeto.profesion (codigo, nombre, activo) VALUES ('796', 'COCINERO', true);
INSERT INTO sujeto.profesion (codigo, nombre, activo) VALUES ('797', 'TEC SUP MERCADOTECN', true);
INSERT INTO sujeto.profesion (codigo, nombre, activo) VALUES ('798', 'TEC MAQUINA Y HERRAM', true);
INSERT INTO sujeto.profesion (codigo, nombre, activo) VALUES ('799', 'TEC INDUSTRIAL', true);
INSERT INTO sujeto.profesion (codigo, nombre, activo) VALUES ('8', 'ACTUARIO', true);
INSERT INTO sujeto.profesion (codigo, nombre, activo) VALUES ('80', 'AYUDANTE', true);
INSERT INTO sujeto.profesion (codigo, nombre, activo) VALUES ('800', 'LA PERMI POR LA LEY ', true);
INSERT INTO sujeto.profesion (codigo, nombre, activo) VALUES ('801', 'TEC SUP EN COMERCIO', true);
INSERT INTO sujeto.profesion (codigo, nombre, activo) VALUES ('802', 'OPERADOR EQ PESADO', true);
INSERT INTO sujeto.profesion (codigo, nombre, activo) VALUES ('803', 'BACH TEC IND ME CO M', true);
INSERT INTO sujeto.profesion (codigo, nombre, activo) VALUES ('804', 'TIMONEL', true);
INSERT INTO sujeto.profesion (codigo, nombre, activo) VALUES ('805', 'BACHILLER EN COMPUTACION', true);
INSERT INTO sujeto.profesion (codigo, nombre, activo) VALUES ('806', 'PUBLICISTA', true);
INSERT INTO sujeto.profesion (codigo, nombre, activo) VALUES ('807', 'MAESTRO MEC ELECTR', true);
INSERT INTO sujeto.profesion (codigo, nombre, activo) VALUES ('808', 'DOCTORA CIENCIAS', true);
INSERT INTO sujeto.profesion (codigo, nombre, activo) VALUES ('809', 'ING CONTAB AUDITORIA', true);
INSERT INTO sujeto.profesion (codigo, nombre, activo) VALUES ('81', 'AZAFATA', true);
INSERT INTO sujeto.profesion (codigo, nombre, activo) VALUES ('810', 'CONTADOR BANCARIO', true);
INSERT INTO sujeto.profesion (codigo, nombre, activo) VALUES ('811', 'ING SISTEMAS Y COMPU', true);
INSERT INTO sujeto.profesion (codigo, nombre, activo) VALUES ('812', 'LIC OPTOMETRIA', true);
INSERT INTO sujeto.profesion (codigo, nombre, activo) VALUES ('813', 'CURANDERO', true);
INSERT INTO sujeto.profesion (codigo, nombre, activo) VALUES ('814', 'MAGISTER', true);
INSERT INTO sujeto.profesion (codigo, nombre, activo) VALUES ('815', 'DR MEDICINA  Y CIRUG', true);
INSERT INTO sujeto.profesion (codigo, nombre, activo) VALUES ('816', 'ARTISTA PROF CALIFIC', true);
INSERT INTO sujeto.profesion (codigo, nombre, activo) VALUES ('817', 'BACH POLI COMER ADMI', true);
INSERT INTO sujeto.profesion (codigo, nombre, activo) VALUES ('82', 'BACHILLER', true);
INSERT INTO sujeto.profesion (codigo, nombre, activo) VALUES ('820', 'BACHILLER SERVICIOS', true);
INSERT INTO sujeto.profesion (codigo, nombre, activo) VALUES ('821', 'ING AUTOMOTRIZ', true);
INSERT INTO sujeto.profesion (codigo, nombre, activo) VALUES ('83', 'BACHILLER AGROPECUARIO', true);
INSERT INTO sujeto.profesion (codigo, nombre, activo) VALUES ('84', 'BACHILLER ARTES PLASTICAS', true);
INSERT INTO sujeto.profesion (codigo, nombre, activo) VALUES ('848', 'DR EN CC EDUCACION', true);
INSERT INTO sujeto.profesion (codigo, nombre, activo) VALUES ('849', 'BACHILLER TECNICO APLICACION INFORMATICA', true);
INSERT INTO sujeto.profesion (codigo, nombre, activo) VALUES ('85', 'BACHILLER CIENCIAS EDUCACION', true);
INSERT INTO sujeto.profesion (codigo, nombre, activo) VALUES ('850', 'LIC CC SOC Y POLIT', true);
INSERT INTO sujeto.profesion (codigo, nombre, activo) VALUES ('851', 'TOPOGRAFO', true);
INSERT INTO sujeto.profesion (codigo, nombre, activo) VALUES ('852', 'BACHILLER MECANDUST', true);
INSERT INTO sujeto.profesion (codigo, nombre, activo) VALUES ('855', 'TLGO ADM SISTE CALIDA', true);
INSERT INTO sujeto.profesion (codigo, nombre, activo) VALUES ('856', 'COSMETOLOGO', true);
INSERT INTO sujeto.profesion (codigo, nombre, activo) VALUES ('86', 'BACHILLER SECRETARIADO', true);
INSERT INTO sujeto.profesion (codigo, nombre, activo) VALUES ('87', 'BACHILLER TECNICO', true);
INSERT INTO sujeto.profesion (codigo, nombre, activo) VALUES ('88', 'BACHILLER TECNICO INDUSTRIAL', true);
INSERT INTO sujeto.profesion (codigo, nombre, activo) VALUES ('89', 'BAILARIN', true);
INSERT INTO sujeto.profesion (codigo, nombre, activo) VALUES ('9', 'ACUICULTOR', true);
INSERT INTO sujeto.profesion (codigo, nombre, activo) VALUES ('90', 'BALANCERO', true);
INSERT INTO sujeto.profesion (codigo, nombre, activo) VALUES ('91', 'BALDOSERO', true);
INSERT INTO sujeto.profesion (codigo, nombre, activo) VALUES ('92', 'BANANERO', true);
INSERT INTO sujeto.profesion (codigo, nombre, activo) VALUES ('93', 'BANQUERO', true);
INSERT INTO sujeto.profesion (codigo, nombre, activo) VALUES ('94', 'BARRENDERO', true);
INSERT INTO sujeto.profesion (codigo, nombre, activo) VALUES ('95', 'BIBLIOTECARIO/A', true);
INSERT INTO sujeto.profesion (codigo, nombre, activo) VALUES ('96', 'BIBLIOTECOLOGO', true);
INSERT INTO sujeto.profesion (codigo, nombre, activo) VALUES ('97', 'BIOLOGO', true);
INSERT INTO sujeto.profesion (codigo, nombre, activo) VALUES ('98', 'BIOQUIMICO', true);
INSERT INTO sujeto.profesion (codigo, nombre, activo) VALUES ('99', 'BIOQUIMICO FARMACEUTICO', true);
INSERT INTO sujeto.profesion (codigo, nombre, activo) VALUES ('A18', 'MECANIQUITO', true);
INSERT INTO sujeto.profesion (codigo, nombre, activo) VALUES ('ABG', 'ABOGADO', true);
INSERT INTO sujeto.profesion (codigo, nombre, activo) VALUES ('ADM', 'ADMINISTRADOR', true);
INSERT INTO sujeto.profesion (codigo, nombre, activo) VALUES ('AF', 'ALFARERO', true);
INSERT INTO sujeto.profesion (codigo, nombre, activo) VALUES ('ANA', 'ANALISTA', true);
INSERT INTO sujeto.profesion (codigo, nombre, activo) VALUES ('ARQ', 'ARQUITECTO', true);
INSERT INTO sujeto.profesion (codigo, nombre, activo) VALUES ('AUD', 'AUDITOR', true);
INSERT INTO sujeto.profesion (codigo, nombre, activo) VALUES ('CON', 'CONTADOR', true);
INSERT INTO sujeto.profesion (codigo, nombre, activo) VALUES ('DER', 'MILITAR', true);
INSERT INTO sujeto.profesion (codigo, nombre, activo) VALUES ('DL', 'DOCTOR EN LEYES', true);
INSERT INTO sujeto.profesion (codigo, nombre, activo) VALUES ('DR', 'DOCTOR', true);
INSERT INTO sujeto.profesion (codigo, nombre, activo) VALUES ('ECO', 'ECONOMISTA', true);
INSERT INTO sujeto.profesion (codigo, nombre, activo) VALUES ('ENF', 'ENFERMER@', true);
INSERT INTO sujeto.profesion (codigo, nombre, activo) VALUES ('EP', 'EMPRESARIO', true);
INSERT INTO sujeto.profesion (codigo, nombre, activo) VALUES ('HJ1', 'SECRETARIA DE COOPERATIVA', true);
INSERT INTO sujeto.profesion (codigo, nombre, activo) VALUES ('ING', 'INGENIERO', true);
INSERT INTO sujeto.profesion (codigo, nombre, activo) VALUES ('JOR', 'JORNALERO', true);
INSERT INTO sujeto.profesion (codigo, nombre, activo) VALUES ('LIC', 'LICENCIAD@', true);
INSERT INTO sujeto.profesion (codigo, nombre, activo) VALUES ('LIP', 'LICENCIADO EDUCACION PARVULARIA', true);
INSERT INTO sujeto.profesion (codigo, nombre, activo) VALUES ('MEC', 'MECANICO', true);
INSERT INTO sujeto.profesion (codigo, nombre, activo) VALUES ('MIL', 'MILITAR', true);
INSERT INTO sujeto.profesion (codigo, nombre, activo) VALUES ('NIN', 'NINGUNA', true);
INSERT INTO sujeto.profesion (codigo, nombre, activo) VALUES ('NNN', 'DECORADOR', true);
INSERT INTO sujeto.profesion (codigo, nombre, activo) VALUES ('OTR', 'OTRAS NO ESPECIFICADAS', true);
INSERT INTO sujeto.profesion (codigo, nombre, activo) VALUES ('P', 'PERMI LEY', true);
INSERT INTO sujeto.profesion (codigo, nombre, activo) VALUES ('PER', 'PERSONAL', true);
INSERT INTO sujeto.profesion (codigo, nombre, activo) VALUES ('PRI', 'EDUCACION PRIMARIA', true);
INSERT INTO sujeto.profesion (codigo, nombre, activo) VALUES ('PRO', 'PROFESIONAL', true);
INSERT INTO sujeto.profesion (codigo, nombre, activo) VALUES ('SEC', 'EDUCACION SECUNDARIA', true);
INSERT INTO sujeto.profesion (codigo, nombre, activo) VALUES ('SEU', 'EDUCACION UNIVERSITARIA', true);
INSERT INTO sujeto.profesion (codigo, nombre, activo) VALUES ('TEC', 'TECNOLOGADO', true);
